### ISSUE TITLE
Issue with AKASHA-provided ENS name

### ISSUE THREAD

**Issue by 42piratas** [AKASHAorg/akasha-world-framework#1039]
**Describe the bug**
I have created an AKASHA-provided ENS name based on my username. The process apparently got stuck in the middle, but the name apparently was registered -- i.e. if I try to register it again, it says "Subdomain already taken", which didn't happen the first time I've tried (when it got stuck in the middle). The option to create the subdomain in my profile is still active, although there's nothing else I could do with it, if I understood correctly, since I cannot change the subdomain name and it's already taken. 

I hope I can still get/link that specific subdomain to my profile 🙏🏽

**To Reproduce**
1. Go to "my-profille"
2. Click on "Edit profile"
3. Click on "Add Ethereum Name"

![image](https://user-images.githubusercontent.com/18232600/113585567-c7bbb280-9602-11eb-8842-b6e3ba6feae2.png)

**Comment by 42piratas** [comment]
@SeverS No, only on production (akasha.ethereum.world)

**Comment by ItsNayabSD** [comment]
Yep. Me too have the same problem.

![akasha_subdomain_taken](https://user-images.githubusercontent.com/6679112/114218453-0c3ea980-9987-11eb-9281-72f5bfefaaa8.png)

**Comment by 42piratas** [comment]
@kenshyx New error now 

![image](https://user-images.githubusercontent.com/18232600/114445015-ed6a2e00-9ba5-11eb-988f-781e9247a0eb.png)

**Comment by kenshyx** [comment]
Can you add include some console printscreens when this happens, thanks!

**Comment by 42piratas** [comment]
@kenshyx 

![image](https://user-images.githubusercontent.com/18232600/114545434-5a2b0a00-9c32-11eb-9cfd-78569116db2b.png)
