### ISSUE TITLE
Getting error "No Web3 Provider found" on Brave Browser

### ISSUE THREAD

**Issue by 42piratas** [AKASHAorg/akasha-world-framework#1052]
**Describe the bug**
Trying to sign up with a new invitation code. Metamask is installed and functional on my Brave, and it is connected to Rinkbey.

**To Reproduce**

1. Go to https://akasha.ethereum.world/social-app/feed
1. Click on "Sign up"
1. Accept terms and conditions
1. Click on "Metamask" > Gets the error

* macOS Big Sur 11.2.3
* Brave 1.20

![image](https://user-images.githubusercontent.com/18232600/113780899-3a618680-9706-11eb-8249-b3e14b2418e7.png)

**Comment by 42piratas** [comment]
attn. @SeverS 

![image](https://user-images.githubusercontent.com/18232600/113783319-f40e2680-9709-11eb-9791-35bb83f11c68.png)

**Comment by 42piratas** [comment]
attn. @SeverS 

![image](https://user-images.githubusercontent.com/18232600/113783384-0be5aa80-970a-11eb-9ad3-eaec80f4d978.png)

**Comment by kenshyx** [comment]
Your account is not connected @42piratas , click on that button where it says `Not connected`

**Comment by 42piratas** [comment]
@kenshyx Sever helped me a bit with this on Basecamp. I've followed his instructions and manually connected* to MM. Still get the same error though. 

*To manually connect, actually one needs to go to the three-dots, then "Connected Sites", then connect manually.

![image](https://user-images.githubusercontent.com/18232600/114172440-0ce62a00-990c-11eb-8866-fad09e84783f.png)

**Comment by kenshyx** [comment]
https://metamask.zendesk.com/hc/en-us/articles/360038596792-Using-Metamask-wallet-in-Brave-browser should fix this

**Comment by 42piratas** [comment]
@kenshyx It solved the problem indeed.

This one is probably another relevant one to add to the FAQ ✊🏽
