### ISSUE TITLE
[onboarding] Error is thrown for the wrong network

### ISSUE THREAD

**Issue by SeverS** [AKASHAorg/akasha-world-framework#1053]
**Describe the bug**

Wrong network error is somehow thrown in the onboarding screen

**To Reproduce**

1. switch to main network
2. try to register

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kenshyx** [comment]
fixed in #1054
