### ISSUE TITLE
Profile pic in menu bar, not the users one. 

### ISSUE THREAD

**Issue by nikoline** [AKASHAorg/akasha-world-framework#1056]
**Describe the bug**
When logged in, and navigating, in the menu bar there is a profile picture in a circle. This opens your profile page. But for some reason it does not show my profile picture, but an amazing one with a cat and a helmet ;) It nice. But its confusing since I was expecting to see another user instead of my own profile when i clicked. 

**To Reproduce**
1. log in '...'
2. navigate '....'
3. top right menu bar profile pic '....'

**Expected behavior**
I expected to see another profile

**Screenshots**
<img width="290" alt="Screenshot 2021-04-07 at 15 59 51" src="https://user-images.githubusercontent.com/13719067/113879509-df3d9b80-97ba-11eb-966a-aa76c0c51a83.png">

**Desktop (please complete the following information):**
 - Brave V1.22.71

**Comment by kenshyx** [comment]
@SeverS can you take a look at this, I know this is a hanging issue after the profile completion.
