### ISSUE TITLE
Uploaded avatar image and cover image not being displayed 

### ISSUE THREAD

**Issue by sheldrake** [AKASHAorg/akasha-world-framework#1057]
**Describe the bug**
I uploaded both an avatar image and cover image on registering on akasha.ethereum.world. It looked like they were being uploaded but neither appears to have worked.

I then clicked to edit my profile and tried uploading both images again. Again, the action 'completed', so to speak i.e. I could see them in the edit profile UI, but this didn't actually work as you can see:

![Screenshot 2021-04-08 at 09 53 50](https://user-images.githubusercontent.com/208643/113990027-f3c87500-9848-11eb-9d65-f4d8147c9f5f.png)

**Desktop (please complete the following information):**
MAC OS Big Sur 11.2.3
FF 87

**Comment by kenshyx** [comment]
This is happening because of the shared ipfs gateway, sometimes the requests are throttled, we need a dedicated node :)

**Comment by kenshyx** [comment]
this should be patched after #1060
