### ISSUE TITLE
I replied to a post, but now my reply is not showing

### ISSUE THREAD

**Issue by sheldrake** [AKASHAorg/akasha-world-framework#1062]
**Describe the bug**
This morning I replied to https://akasha.ethereum.world/social-app/post/01f2trtgxs1e5v3fgfvpm76trh before Martin did. Now, as you can see, my reply is not shown.

**Expected behavior**
I would expect to see my reply.

**Desktop (please complete the following information):**
 - MAC OS Big Sur 11.2.3
 - FF 87

**Comment by kenshyx** [comment]
Please include also a console screenshot next time, we need it to check for possible client-side errors :)

**Comment by sheldrake** [comment]
Will do.

But just checking. In this instance are you talking about a console screenshot of when I posted the reply.

Or hours later when I noticed it was not in the post's thread?

If you can't see it, and I can't see it, what would the console screenshot tell you?
