### ISSUE TITLE
Trending Topics Counter 

### ISSUE THREAD

**Issue by 42piratas** [AKASHAorg/akasha-world-framework#1069]
The number of trending topics is not increasing following the number of posts using the respective hashtag. All of them appear with "1".

![image](https://user-images.githubusercontent.com/18232600/114545101-eab51a80-9c31-11eb-9e6e-ec5b40bf2571.png)

**Comment by kenshyx** [comment]
this was adjusted in #1070 , it was using only the most recent 20 tags created
