### ISSUE TITLE
Customer-reported bugs

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1073]
R writes:

Hey,
 
 I have noticed a bug that appears every now and then. It occurs under replies to a posts. It seems that 2 comments collide in one (a picture of this is below). Refresh solves the issue. I am using Windows 64x machine with Brave browser. Also when I was firstly making the profile, the website was unable to load my Metamask wallet with the Brave Shields turned on. Turning this thing off worked. However I was too excited to take a screenshot.
 
Otherwise akasha seems absolutely great. Love you work.

And attaches:

![image001](https://user-images.githubusercontent.com/15471332/114626025-be70bc80-9c78-11eb-8544-5bde1ab1861c.png)

**Comment by collectivenectar** [comment]
I'll add to this, screenshot included, I am on OSX 10.15, using Chrome v89.0.4389.128. Same as above, seems to happen in replies to a post.
<img width="1411" alt="Screen Shot 2021-04-14 at 10 58 26" src="https://user-images.githubusercontent.com/63463014/114737007-e4fd2900-9d46-11eb-9da8-0de106ada7be.png">

**Comment by ggolcher** [comment]
Thanks for adding to this @collectivenectar! Our engineers have identified the issue and are working on it as we speak!
