### ISSUE TITLE
Discord invite link in the "Send us feedback" menu expired

### ISSUE THREAD

**Issue by etzm** [AKASHAorg/akasha-world-framework#1087]
**Describe the bug**
I discovered that the "Join in Discord" link points to an expired invite. 
Tested on 2 different devices, so it seems really not working anymore.

**Comment by afterlife-labs** [comment]
Thanks for spotting this! 🙏 We'll implement a permanent invitation link ASAP.

**Comment by etzm** [comment]
From @afterlife-labs : https://discord.gg/A5wfg6ZCRt
