### ISSUE TITLE
Stacked subscription entries

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1134]
nayabsd says:

Overlapping bookmarked posts

![image](https://user-images.githubusercontent.com/15471332/116563138-5d2c2880-a8c9-11eb-8f24-9077ed4964af.png)

**Comment by ItsNayabSD** [comment]
You can include my official Github id here :)  ... @ggolcher 

![bookmarks_page_overlap_posts](https://user-images.githubusercontent.com/6679112/116577438-16244e80-a92e-11eb-8a09-8f70cad88d6e.png)

**Comment by ggolcher** [comment]
Great! Thank you!
