### ISSUE TITLE
The article cannot be displayed

### ISSUE THREAD

**Issue by tyevlag** [AKASHAorg/akasha-world-framework#1245]
**Describe the bug**
Click the article on the home page to jump to the full text, and a blank page will be displayed

**To Reproduce**
1. Go to 'page main'
2. Click on 'any article'
3. See error

**Expected behavior**
Show full text content

**Screenshots**
![1628172676(1)](https://user-images.githubusercontent.com/9290978/128364704-a7e3506d-97e8-4f86-9e9f-72ac199bbf64.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 90.0.2 (64 bit)

**Additional context**
In Develop Tool:
Uncaught (in promise) TypeError: (new TypeError("NetworkError when attempting to fetch resource.", "")) is not iterable
    getPost https://akasha.ethereum.world/apps/akasha/ui_hooks_lib_index_js.js:1

**Comment by kenshyx** [comment]
This was a temporary network issue, thank you for your report!
