### ISSUE TITLE
[iOS Mobile Web]  There is no Report User UI when the user taps the Report button on the Profile UI while using Safari and Google Chrome on an iOS device.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1293]
**Describe the bug**
When the user taps the Report button on the Profile UI while using Safari and Google Chrome on an iOS device, the Report User UI does not appear.

**To Reproduce**
1. On the Profile UI of the user, tap the menu beside the Follow button.
2. Select the Report button.
3. Observe the behavior of the site.

**Expected behavior**
The Report User UI should appear upon tapping the Report button on Profile UI.

**Attachment**
https://user-images.githubusercontent.com/79607355/134145051-2cc3cf61-50f2-4a35-bf02-a43029fae64c.mp4

**Device:**
 - iPhone XR
 - OS: 15
 - Browser: Safari
 - Version: 15
 - Browser : Google Chrome
 - Version : 77.3865.103

**Additional context**
The issue does not occur on the below devices and browsers:

Sony Xperia 1 | OS 11
    - Google Chrome 77.3865.103
Huawei P20 | OS 10
    - Chrome Version 93.0.4577.82
    - MetaMask Browser 3.3.0
Toshiba Dynabook | Windows 10 pro
    - Chrome Version 93.0.4577.82
    - Firefox Version 92.0
iPhone XR | OS 15
    - Firefox 19.1
    - MetaMask Browser 3.3.0

**Wallet Used:**
Metamask

EP(ACP)

cc: @ggolcher

**Comment by EPforAkasha** [comment]
Update

Here's the Console Logs for the Report Profile issue.

Safari: [Safari_ReportButtonIssue_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7252376/Safari_ReportButtonIssue_iOSLogs.txt)
Google Chrome: [GoogleChrome_ReportButtonIssue_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7252381/GoogleChrome_ReportButtonIssue_iOSLogs.txt)

Note:
- The issue does not occur when using the iOS MetaMask Browser.

Devices Used:
iPhone X | OS 14.7.1

Browsers Used:
Safari | Version 14
Google Chrome | Version 93.0.4577.78

(AAP)

**Comment by ggolcher** [comment]
@kenshyx Why is this hard to fix?

This seems like it would be important to fix before launch.

**Comment by kenshyx** [comment]
it's hard to replicate
