### ISSUE TITLE
[iOS Mobile Web] The Ethereum World webpage is not loading when accessing the 'https://ethereum-world.netlify.app/AKASHA-app/feed' weblink on any mobile browser using the iPhone 7 | OS 13.3.1 device.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1295]
**Describe the bug**
When the user accesses the 'https://ethereum-world.netlify.app/AKASHA-app/feed' weblink while using any mobile browser (ex: Google Chrome) on iPhone 7 | OS 13.3.1 device, the Ethereum World webpage does not load.

**To Reproduce**
1. Open any mobile browser (ex: Google Chrome).
2. Enter or paste the 'https://ethereum-world.netlify.app/AKASHA-app/feed' weblink and then Go.
3. Check if the Ethereum World webpage will load.

**Expected behavior**
The Ethereum World webpage should load properly when the 'https://ethereum-world.netlify.app/AKASHA-app/feed' weblink is accessed on any mobile browser using the iPhone 7 | OS 13.3.1 device.

**Attachment**
https://user-images.githubusercontent.com/79607355/134151740-5e9e3c06-c5a8-4cf0-a8d1-4bb084c7cf5c.mp4

**Device Used:**
 - iPhone 7
 - OS: 13.3.1
 - Browsers and Versions: 
 -- Google Chrome | Version 93.0.4577.78
 -- Safari | Version 13
 -- Firefox | Version 37.0 (5971)
 -- MetaMask browser | Version 3.3.0 (777)

**Additional context**
The issue does not occur on the below devices and browsers:
- iPhone XR | OS 15
-- Safari | Version 15
-- Google Chrome Version 93.0.4577.78
- Sony Xperia 1 | OS 11
-- Google Chrome | Version 77.3865.103
- Huawei P20 | OS 10
-- Google Chrome Version 93.0.4577.82
-- MetaMask Browser Version 3.3.0 (777)

**Wallet Used:**
Metamask (Web Extension and App)

EP (STFG)

cc: @ggolcher

**Comment by kenshyx** [comment]
This link doesn't exist, this is an old link most likely from 4-5 months ago. The updated link for the AKASHA app is https://ethereum-world.netlify.app/social-app/feed

**Comment by ggolcher** [comment]
Ack, this is my fault. I started with a copy-paste of the previous engagement email and modified it.

I overlooked that the addresses had changed. I've written to them to make this clear.
