### ISSUE TITLE
The Block button is not available on the Report Submission modal.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1296]
**Describe the bug**
When the user reports an account, there is no Block button on the Report Submission modal.

**To Reproduce**
1. On the Profile UI of the user, tap the menu beside the Follow button.
2. Select the Report button.
3. Select a reason on Report User UI.
4. Tap the Report button.
5. Observe the Report Submission modal.

**Expected behavior**
There should be a Block button on the Report Submission modal.

**Screenshots**

![NoBlockButton](https://user-images.githubusercontent.com/79607355/134158032-556b880e-007a-45b4-9986-6f68fad422bb.PNG)

![MobileNOBlockButton](https://user-images.githubusercontent.com/79607355/134158044-46cd16a6-540d-4119-9f71-df8923bad7d2.png)

**Desktop/Laptop:*
 - Toshiba Dynabook
 - OS: Windows 10 pro
 - Browser: Google Chrome
 - Version 93.0.4577.82
 - Browser: Firefox Version
 - Version 92.0

**Smartphone:**
 - Device: Sony Xperia 1
 - OS: 11
 - Browser Google Chrome
 - Version 77.3865.103

 - Device: Huawei P20
 - OS: 10
 - Browser Google Chrome
 - Version 93.0.4577.82
 - Browser MetaMask 
 - Version 3.3.0

 - Device: iPhone XR
 - OS: 15
 - Browser Mozilla Firefox
 - Version 19.1
 - Browser MetaMask
 - Version 3.3.0

**Wallet Used:**
Metamask

EP(ACP)

cc: @ggolcher

**Comment by ggolcher** [comment]
Block has not been implemented yet
