### ISSUE TITLE
The reported account's post does not have a Reported note on the Feed UI.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1297]
**Describe the bug**
When the user reports an account, the reported account's post does not have a Reported note and still visible on the Feed UI.

**To Reproduce**
1. Report an account.
2. Go to the Feed UI and look for the account's post.
3. Observe the reported account's post.

**Expected behavior**
The reported account's post should have a Reported note on the Feed UI.

**Attachment**
https://user-images.githubusercontent.com/79607355/134167087-f0e9ec6b-6ef5-4f6b-a406-9316007ee9d5.mp4

**Desktop/Laptop:**

    Toshiba Dynabook
    OS: Windows 10 pro
    Browser: Google Chrome
    Version 93.0.4577.82
    Browser: Firefox Version
    Version 92.0

**Smartphone:**

    Device: Sony Xperia 1
    OS: 11
    Browser Google Chrome
    Version 77.3865.103

    Device: Huawei P20
    OS: 10
    Browser Google Chrome
    Version 93.0.4577.82
    Browser MetaMask
    Version 3.3.0

    Device: iPhone XR
    OS: 15
    Browser Mozilla Firefox
    Version 19.1
    Browser MetaMask
    Version 3.3.0
    Browser Safari
    Version 15
    Browser Google Chrome
    Version 77.3865.103

**Wallet Used:**
Metamask

EP(ACP)

cc: @ggolcher

**Comment by EPforAkasha** [comment]
Updating Ticket. The team was advised to leave the ticket Open for future reference

https://www.sketch.com/s/bb1df12e-25c7-470d-a5fb-7cea8a524a8e/a/MyW7Rwa

EP (ENC)

**Comment by ghost** [comment]
Opening for future reference, as advised above
