### ISSUE TITLE
The posts do not have a Share option on the Feed UI.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1298]
**Describe the bug**
When the user accesses the Feed UI and then scrolls down through the posts, the Share option is not available.

**To Reproduce**
1. Go to the 'https://ethereum-world.netlify.app/AKASHA-app/feed' webpage and then log in to an account.
2. When the Feed UI loads, scroll down through the available posts.
3. Check if the Share option is available.

**Expected behavior**
The Share option should be available for the posts on the Feed UI.

**Screenshots**
Mobile Browser:  
 ![MobileBrowser_MissingShareOption_SC](https://user-images.githubusercontent.com/79607355/134176537-2f4ed999-13e7-4557-b1a0-90f69c54c97f.jpg)

Web Browser: 
![WebBrowser_MissingShareOption_SC](https://user-images.githubusercontent.com/79607355/134176577-07d111d6-e30e-4c3d-bf52-f72505c73a5f.PNG)

**Desktop/Laptop:**
 - Toshiba Dynabook | Windows 10 pro
 -- Chrome Version 93.0.4577.82
 -- Firefox Version 92.0
 - Desktop | Windows 10 Home
 -- Chrome Version 93.0.4577.82
 -- Firefox Version 92.0
 -- Microsoft Edge Version 93.0.961.52

**Smartphones:**
 - iPhone 7 | OS 13.3.1 | 
 -- Google Chrome | Version 93.0.4577.78
 -- Safari | Version 13
 -- Firefox | Version 37.0 (5971)
 -- MetaMask browser | Version 3.3.0 (777)
 - iPhone XR | OS 15
 -- Safari | Version 15
 -- Google Chrome Version 93.0.4577.78
 - Sony Xperia 1 | OS 11
 -- Google Chrome | Version 77.3865.103
 - Huawei P20 | OS 10
 -- Google Chrome Version 93.0.4577.82
 -- MetaMask Browser Version 3.3.0 (777)

**Additional context**
Here is the attached screenshot of the spec design for reference:
![Reference_ShareOptionOnPosts_SC](https://user-images.githubusercontent.com/79607355/134176773-5b66c81d-c7c0-4798-bf8c-e895f6516ed7.PNG)

**Wallet Used:**
Metamask (Web Extension and App)

EP (STFG)

cc: @ggolcher

**Comment by ggolcher** [comment]
We have not implemented share yet
