### ISSUE TITLE
[Android Mobile Web] The "Subscribe" text and assets are exceeding its placeholder button on the Main UI when using the Samsung Galaxy Tab S6 Lite device.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1305]
**Describe the bug**
When the user accesses the Main UI while using the Samsung Galaxy Tab S6 Lite on any browser, the "Subscribe" text and assets are exceeding its placeholder button.

**To Reproduce**
1. Open any mobile browser (ex: Google Chrome).
2. Go to the 'https://ethereum-world.netlify.app/social-app/feed' webpage and then log in to an account.
3. Observe the "Subscribe" button.

**Expected behavior**
- The "Subscribe" text and asset should be displayed properly on its placeholder button.

**Screenshots**
![Subscribe_Button_Exceeding](https://user-images.githubusercontent.com/79607355/134336847-4e252f23-82bc-4d1d-8521-85da799979f1.jpg)

Device Used:
Samsung Galaxy Tab S6 Lite | OS 11
- MetaMask Browser
- Chrome Version 93.0.4577.82

- The issue was not able to check on the iOS mobile browser due to the unavailability of iOS as of the moment.
- The issue does not occur on the below devices and browsers:
Realme C3 | OS 10
-- Google Chrome Version 93.0.4577.82
--  MetaMask Browser Version 3.3.0 (777)
Huawei P20 | OS 10
-- Google Chrome Version 93.0.4577.82
-- MetaMask Browser Version 3.3.0 (777)
-- imToken Browser Version 2.9.6.1387

Wallet Used:
- Metamask Wallet.

EP (ENC)

cc: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch

**Comment by kenshyx** [comment]
this was already fixed
