### ISSUE TITLE
[Desktop Web] The Hover Icon is not appearing on an edited post.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1306]
**Describe the bug**
When the user edits a post, the Hover Icon is not appearing on that edited post.

**To Reproduce**
1. Open any web browser (ex: Google Chrome).
2. Go to the 'https://ethereum-world.netlify.app/social-app/feed' webpage and then log in to an account.
3. On the Feed UI, edit a post.
4. After successfully editing a post, check if the Hover Icon is displayed.

**Expected behavior**
The Hover Icon should be displayed on an edited post.

**Attachment**
https://user-images.githubusercontent.com/79607355/134340841-4101b369-0e8e-4f5b-8804-ec4b3818e3ae.mp4

**Peripherals Used:**
- Desktop | Windows 10 Home
-- Chrome Version 93.0.4577.82
-- Firefox Version 92.0
-- Microsoft Edge Version 93.0.961.52
- Desktop | Windows 10 Pro
-- Chrome Version 93.0.4577.82
-- Firefox Version 92.0
-- Microsoft Edge Version 93.0.961.52

**Additional context**
-  The issue was not able to check on the mobile browser due to this issue: https://github.com/AKASHAorg/akasha-world-framework/issues/1309
- Here is the attached screenshot of the design spec for reference:
![Reference_EditedPostHoverIconSC](https://user-images.githubusercontent.com/79607355/134341138-05ddd0be-33e8-4dea-81c5-5e839098a676.PNG)
 
**Wallets Used:**
- MetaMask Web Extension
- Nifty Wallet Web Extension

EP (STFG)

cc: @ggolcher

**Comment by kenshyx** [comment]
implemented in #1341
