### ISSUE TITLE
[Mobile Web] The Edit button is missing on the Overflow Menu and the reply post.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1309]
**Describe the bug**
When the user taps the Meatball Menu on the Overflow Menu or the reply post, the Edit button is missing.

**To Reproduce**
1. Go to the 'https://ethereum-world.netlify.app/social-app/feed' webpage and then log in to an account.
2. Post on the Overflow Menu.
3. Tap the Meatball Menu of the post and observe.
4. Reply to the post.
5. Tap again the Meatball Menu of the reply post and observe

**Expected behavior**
- The Edit button should appear upon tapping the Meatball menu on both the Overflow Menu and replied post.

**Screenshots**
https://user-images.githubusercontent.com/79607355/134351172-d8736087-7d01-477d-b37c-acc8b66fb576.mp4

Devices Used:
Samsung Galaxy Tab S6 Lite | OS 11
-- MetaMask Browser
-- Chrome Version 93.0.4577.82
Realme C3 | OS 10
-- Google Chrome Version 93.0.4577.82
-- MetaMask Browser Version 3.3.0 (777)
Huawei P20 | OS 10
-- Google Chrome Version 93.0.4577.82
-- MetaMask Browser Version 3.3.0 (777)
-- imToken Browser Version 2.9.6.1387

Additional context
- The issue was not able to check on the iOS mobile browser due to the unavailability of iOS as of the moment.

Wallet Used:
- Metamask Wallet.
- imToken Wallet

EP (ENC)

CC: @ggolcher

**Comment by ggolcher** [comment]
![Screen Shot 2021-10-18 at 1 47 14 PM](https://user-images.githubusercontent.com/15471332/137789109-48f3608a-9218-4c14-90d2-a3d070bea055.png)
![Screen Shot 2021-10-18 at 1 47 33 PM](https://user-images.githubusercontent.com/15471332/137789112-e4d6ff93-08f4-4d7e-8d58-65af70dd2ba5.png)
The visual treatment for Edit Post and Edit Reply is broken on mobile

**Comment by quininez** [comment]
There was an issue with the edit post button not rendering full width which I fixed now, but the fact that the edit button is displayed as a separate button from delete reply is due to us loading it through a different mechanism, as an extension. This is a work in progress for us and will be adjusted as we transition the entire popover content to be loaded in the same manner.

**Comment by ggolcher** [comment]
This is not a blocker to launch
