### ISSUE TITLE
An error "Sorry, there is an error validating the username. Try again later" is appearing when signing-up a new account.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1314]
**Describe the bug**
Upon signing up a new account on a public moderation App, an error "Sorry, there is an error validating the username. Try again later" is appearing upon inputting characters on the username section.

**To Reproduce**
1. Open any browser (ex: Google Chrome).
2. Go to the 'https://ethereum-world.netlify.app/ webpage and then log in to the metamask account.
3. Tap the sign-up button.
4. Input the referral code.
5. Fill up the 'Create Profile' UI.
6. Observe if the user will be able to sign up for an account.

**Expected behavior**
The user should be able to create an account on the public moderation app.

**Attachments*
*If applicable, add screenshots to help explain your problem.
![Error_SignUp_Public_ModerationApp](https://user-images.githubusercontent.com/79607355/134593817-2d9d9b40-0269-467d-ad3a-e51c66fa83a9.JPG)

https://user-images.githubusercontent.com/79607355/134593885-f0ee3aae-c1c7-427d-b8a6-06a19b46298a.mp4

**Desktop (please complete the following information):**
Dell Optiplex 3040 | Windows 10 Pro
 -Google Chrome Version 93.0.4577.82
 -Mozilla Firefox Version 92.0.1 (64-bit)
Asus FX553VDWindows 10 Pro
 -Google Chrome Version Version 93.0.4577.82
 -Microsoft Edge 44.18362.387.0

**Smartphone (please complete the following information):**
iPad Pro 12.9 inch | 15
 -Safari Browser 15
HTC U12+ | 8
 -Metamask Browser

**Additional context**

**Wallets Used:**
 - MetaMask Web Extension and App

(NJPDR)

cc:@ggolcher

**Comment by ghost** [comment]
Checked this, front-end validation is working fine and this shouldn't be possible. My assumption is a network error.

**Comment by EPforAkasha** [comment]
The network error when creating a profile is still being encountered.

Device Used:
AMD Radeon RX Vega 11 | Windows 10 Pro 

Browser Used:
Firefox | 93.0


![NetworkError](https://user-images.githubusercontent.com/79607355/137554813-1a28e456-6822-43f6-a27e-3ee5a416a499.png)


[AAT]

**Comment by kenshyx** [comment]
This is happening because the network was not changed to `rinkeby`(id: 4).

**Comment by ggolcher** [comment]
This is not a blocker to launch

**Comment by kenshyx** [comment]
this is actually an important one to fix :D

**Comment by SeverS** [comment]
fixed in https://github.com/AKASHAorg/akasha-world-framework/commit/c5de98676266dd8269a18d1d59044021e1cc745e
