### ISSUE TITLE
An Error page appears after clicking "Kept" button on the Moderated tab of the Moderator dashboard.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1315]
**Describe the bug**
When the user goes to the Moderated tab of the Moderator dashboard, the page will turn into an Error page upon clicking the "Kept" button.

**To Reproduce**
1. Open the Moderator dashboard(https://ethereum-world.netlify.app/moderation-app).
2. Go to the Moderated tab.
3. Click the "Kept" button.

**Expected behavior**
All of the Moderated posts that are on the "Kept" UI should be visible after clicking the "Kept" button.

**Screenshots**
![Error_page](https://user-images.githubusercontent.com/79607355/134597116-8443249a-920c-44d7-b875-3db186aec6eb.png)
**Desktop:**
 Windows 10 Pro
 - Google Chrome 93.0.4577.82
 - Firefox92.0 (64-bit)
 - Mircosoft Edge93.0.961.52 (Official build) (64-bit)

**Smartphone:**
Honor Play | OS 9
 - Chrome Version 94.0.4606.50
 - MetaMask V3.3.0 (777)

**Additional context**

**Wallets Used:**
- MetaMask Web Extension and App

-AMLT

CC: @ggolcher

**Comment by kenshyx** [comment]
fixed in #1335
