### ISSUE TITLE
The subtext is not appearing upon hovering the cursor on the account image on the Moderated item lists.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1316]
**Describe the bug**
Upon hovering the cursor on the account image on the Moderated item lists, the subtext is not appearing.

**To Reproduce**
1. Open any browser (ex: Google Chrome).
2. Go to the 'https://ethereum-world.netlify.app/ webpage and then log in to the metamask account.
3. Tap the sign-in button.
4. Tap the user's profile image.
5. Tap the Moderation History button.
6. Hover the cursor on the profile image displayed.

**Expected behavior**
The subtext should be displayed upon hovering the cursor on the account image.

**Screenshots**

https://user-images.githubusercontent.com/79607355/134612064-31839c8b-e5be-4c35-9eec-14ffb41720b9.mp4

**Desktop (please complete the following information):**
Dell Optiplex 3040 | Windows 10 Pro
 -Google Chrome Version 93.0.4577.82
Mozilla Firefox Version 92.0.1 (64-bit)
 -Asus FX553VDWindows 10 Pro
Google Chrome Version Version 93.0.4577.82
 -Microsoft Edge 44.18362.387.0

**Smartphone (please complete the following information):**
iPad Pro 12.9 inch | 15
 -Safari Browser 15
HTC U12+ | 8
-Metamask Browser

**Additional context**
Here is the attached screenshot of the design spec for reference:
![image](https://user-images.githubusercontent.com/79607355/134612981-ed09766a-f828-430a-a099-46b0af1089ba.png)

**Wallet Used:**
MetaMask Web Extension and App

(NJPDR)

cc:@ggolcher

**Comment by ghost** [comment]
Fixed with #1378
