### ISSUE TITLE
The Moderator is unable to Delist a post.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1317]
**Describe the bug**
When the Moderator tapped the "Make a Decision" button on a post and tried to Delist the post, the "Delist" button will become enabled again and the post will not be moved.

**To Reproduce**
1. Open the Moderator dashboard(https://ethereum-world.netlify.app/moderation-app).
2. Select a post.
3. Tap the "Make a Decision" button and select "Delist".
4. Enter a reason under the "Evaluation" section and tap "Delist".

**Expected behavior**
The Moderator should always be able to Delist any post.

**Screenshots**
https://user-images.githubusercontent.com/79607355/134614128-254c4ef9-f0b5-4231-ba10-3916ec39aa85.mp4

**Desktop:**
 Windows 10 Pro
 - Google Chrome 93.0.4577.82
 - Firefox92.0 (64-bit)
 - Mircosoft Edge93.0.961.52 (Official build) (64-bit)

**Smartphone:**
Honor Play | OS 9
 - Chrome Version 94.0.4606.50
 - MetaMask V3.3.0 (777)

**Additional context**

**Wallets Used:**
- MetaMask Web Extension and App

-AMLT

CC: @ggolcher

**Comment by SeverS** [comment]
add error handling to the report modal
