### ISSUE TITLE
The 'Moderation items' is not appearing on the Moderation History UI.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1319]
**Describe the bug**
Upon accessing the Moderation History, the number of Moderation items was listed but the items were not displayed.

**To Reproduce**
1. Open any browser (ex: Google Chrome).
2. Go to the 'https://ethereum-world.netlify.app/ webpage and then log in to the metamask account.
3. Tap the sign-in button.
4. Tap the user's profile image.
5. Tap the Moderation History button.
6. Observe if the Moderated items will appear.

**Expected behavior**
The Moderated items should be displayed upon accessing the Moderation History.

**Screenshots**

https://user-images.githubusercontent.com/79607355/134614051-6464dc38-7e62-4445-9b38-c117e29312fa.mp4

**Desktop (please complete the following information):**
Dell Optiplex 3040 | Windows 10 Pro
-Google Chrome Version 93.0.4577.82
Mozilla Firefox Version 92.0.1 (64-bit)
-Asus FX553VDWindows 10 Pro
Google Chrome Version Version 93.0.4577.82
-Microsoft Edge 44.18362.387.0

**Smartphone (please complete the following information):**
iPad Pro 12.9 inch | 15
 -Safari Browser 15
HTC U12+ | 8
 -Metamask Browser

**Additional context**

**Wallet Used:**
MetaMask Web Extension and App

(NJPDR)

cc:@ggolcher

**Comment by scaleop09** [comment]
![Captureregjkqlehrquie](https://user-images.githubusercontent.com/90257562/136773355-b5cc17c2-8340-4588-9ee4-7bd506904673.PNG)
![Uploading CapturrgZRGHrgomqZGRzzgGe.PNG…]()

**Comment by EPforAkasha** [comment]
The issue is still occurring. Adding new attachments for reference.

https://user-images.githubusercontent.com/79607355/137404981-1fbfe7c9-dccd-427a-8bb6-b129be33189d.mp4

[Empty_ModerationHistory.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7349726/Empty_ModerationHistory.txt)

**Devices Used:**
Dell Optiplex 3040 | Windows 10 Pro
-Firefox Version 92.0.1
Asus FX553VD | Windows 10 Pro
-Chrome Version 94.0.4606.81
Honor Play | 9
-Firefox Version 93.1.0
iPad Pro 12.9 inch | 15.0.2
-Safari 15.0.2
iPad 9.7 (5th Gen) | 13.6

Weblink:
https://ethereum-world.netlify.app/moderation-app/history

(NJPDR)

**Comment by kenshyx** [comment]
this was fixed in https://github.com/AKASHAorg/akasha-world-framework/commit/4126f1a884ea9114d86461202d4099d446b25f00
