### ISSUE TITLE
OpenGraph preview is lost when editing a post

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1321]
**Describe the bug**
Editing a post with an OpenGraph link loses the preview. If saving, the preview is lost.

**To Reproduce**
1. Draft a post with a link like https://www.linkedin.com/feed/update/urn:li:activity:6847128194399768576/
2. Edit the post -- _the preview is lost_
3. Save the edited post -- the preview does not appear

**Expected behavior**
I expect the editing dialog to keep the preview, and saving to keep the preview if the link remains. **Also, the post button is disabled**

**Screenshots**
<img width="1102" alt="Screen Shot 2021-09-24 at 8 38 17 AM" src="https://user-images.githubusercontent.com/15471332/134683819-2d787c4d-58f7-4fe9-a648-3878acca6d2a.png">

**Desktop (please complete the following information):**
Mac 11.6, Chrome 93, MetaMask

**Comment by kenshyx** [comment]
fixed in #1339
