### ISSUE TITLE
OpenGraph Preview is not resizing to fit the image in the preview

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1322]
**Describe the bug**
There is a weird space at the bottom of the OpenGraph preview image.

**To Reproduce**
Add this link to a post: https://www.linkedin.com/feed/update/urn:li:activity:6847128194399768576/

**Expected behavior**
The container should fit the image

**Screenshots**
<img width="846" alt="Screen Shot 2021-09-24 at 8 33 42 AM" src="https://user-images.githubusercontent.com/15471332/134684318-295e64fa-c9ed-4717-b32e-7fdfa8409f08.png">

**Desktop (please complete the following information):**
macOS 12.6, Chrome 93, MetaMask

**Comment by ggolcher** [comment]
This should not be an enhancement. It's a matter of resizing the OpenGraph item.

I do agree it's not a blocker to launch.

**Comment by SeverS** [comment]
fixed in #1450
