### ISSUE TITLE
Small image shows a broken preview

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1323]
**Describe the bug**
Uploading a really-small image breaks the preview in editing a post

**To Reproduce**
1. Steps to reproduce the behavior:
2. Start a post
3. Upload a miniscule image
4. The remove X is not visible

**Expected behavior**
The preview container should have a minimum size.

**Screenshots**
<img width="719" alt="Screen Shot 2021-09-24 at 8 51 54 AM" src="https://user-images.githubusercontent.com/15471332/134686167-c3ab7831-5c6e-4e9f-baa0-c7995578d292.png">

**Desktop (please complete the following information):**
macOS 12.6, Chrome 93, MetaMask

**Comment by kenshyx** [comment]
fixed in #1339
