### ISSUE TITLE
An "Error in moderation app" page appears whenever the user refreshes the Moderation page.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1329]
**Describe the bug**
When the Moderator tries to refresh the page, the Moderator will be prompted by an "Error in moderation app" page.

**To Reproduce**
1. Open the Moderator dashboard(https://ethereum-world.netlify.app/moderation-app).
2. Refresh the page.

**Expected behavior**
There should be no error pages appearing on the website.

**Screenshots**
![Error_in_moderation_app_page](https://user-images.githubusercontent.com/79607355/134750142-62c0e3e8-41fa-4ad1-9edc-778a4f575433.png)

https://user-images.githubusercontent.com/79607355/134750144-b8b070e8-a9ce-4d1c-9e00-95981778b2a3.mp4

**Desktop:**
 Windows 10 Pro
 - Google Chrome 93.0.4577.82
 - Firefox92.0 (64-bit)
 - Mircosoft Edge93.0.961.52 (Official build) (64-bit)

**Smartphone:**
Honor Play | OS 9
 - Chrome Version 94.0.4606.50
 - MetaMask V3.3.0 (777)

**Additional context**

**Wallets Used:**
- MetaMask Web Extension and App

**Note**
The issue also occurs when the user taps the Moderated tab on the Moderation page.

-AMLT

CC: @ggolcher

**Comment by EPforAkasha** [comment]
Updating Ticket. Kindly see the newly attached logs and screenshots


[Error in moderation app_Logcat.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7252484/Error.in.moderation.app_Logcat.txt)
![Error in moderation app](https://user-images.githubusercontent.com/79607355/135282988-d1dbdc5d-17c4-4bd3-b06a-b339a13833f1.jpg)

EP (ENC)

**Comment by kenshyx** [comment]
fixed in #1335
