### ISSUE TITLE
[Mobile Web] The Filter tabs are still displayed in the Entry details on the Moderation History page.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1331]
**Describe the bug**
On the Moderation History page, the Filter tabs are still displayed in the Entry details even though the filter tabs have no function.

**To Reproduce**
1. Launch any of the browser applications.
2. Go to the "https://ethereum-world.netlify.app/moderation-app/history" webpage.
3. Tap any of the entry items.
4. Observe the filter tabs.

**Expected behavior**
The webpage should not display the filter tabs on the Entry details.

**Attachments**
![Screenshot_Reference](https://user-images.githubusercontent.com/79607355/134795788-1dea8d81-1304-4c42-8f1f-fa7d81fea93d.JPG)
![Screenshot_FilterTabsDisplayOnEntryDetails](https://user-images.githubusercontent.com/79607355/134795792-4fa1fda4-ba74-4932-87f4-ca2bec0af562.PNG)

**Devices Used:**
 - Google Pixel 3 XL || OS: 11
 - iPad 10.2 inch (2020) (8th Gen)
 - Android Browsers and Versions:
 -- Google Chrome || Version 93.0.4577.82
 -- Firefox || Version 92.1.1
 -- MetaMask Browser || Version 3.3.0
 - iOS Browsers and Versions:
 -- Google Chrome || Version 90.0.4430.216
 -- Firefox || Version 34.0 (4920)
 -- Safari || Version 15
 -- MetaMask Browser || Version 3.3.0

**Additional context**
The issue only occurs on:
 - Android Browsers:
 -- Google Chrome || Version 93.0.4577.82
 -- Firefox || Version 92.1.1
 -- MetaMask Browser || Version 3.3.0
 - iOS Browser:
 -- MetaMask Browser || Version 3.3.0

EP (CFG)

@ggolcher

**Comment by kenshyx** [comment]
@josenriagu
