### ISSUE TITLE
Emoji Editor modal appears in "wrong layer", can't select

### ISSUE THREAD

**Issue by etzm** [AKASHAorg/akasha-world-framework#1361]
**Describe the bug**
I can not add an emoji. The emoji modal opens below the editor pone, but it is "greyed out"

**To Reproduce**
1. Go to Editor
2. Click on 'emoji

![Screenshot 2021-10-08 at 10 51 37](https://user-images.githubusercontent.com/31589705/136528198-cfc2c1fe-cca2-4f1d-b0d9-a1bff55080a5.png)

**Expected behavior**
emoji window in right level. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 11.6
 - Browser Chrome browser

**Comment by kenshyx** [comment]
patched on #1364
