### ISSUE TITLE
Moderation Reason choices: Only "other" can be selected

### ISSUE THREAD

**Issue by etzm** [AKASHAorg/akasha-world-framework#1362]
**Describe the bug**
I believe the screenshot tells it all: 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
![Screenshot 2021-10-08 at 11 01 07](https://user-images.githubusercontent.com/31589705/136529201-736ae61f-d503-4de9-b16c-dc19ebf1f601.png)

**Comment by kenshyx** [comment]
fixed after https://github.com/AKASHAorg/akasha-world-framework/commit/2c9b819c2c639fa8d6082d1977bd770270824cd2
