### ISSUE TITLE
Sign In Prompt Wrong

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1370]
**Describe the bug**
The sign in prompt for any action

**To Reproduce**
Take any actions that require user to sign in

**Expected behavior**
I expect to get the full sign in prompt screen

**Device**
macOS 12.6, Chrome 94, MetaMask

**Screenshots*
![Screen Shot 2021-10-11 at 1 06 22 PM](https://user-images.githubusercontent.com/15471332/136837616-25259e12-a41c-4758-b5d7-64a4f4d627dd.png)

**Comment by kenshyx** [comment]
Please reference also the design file, it helps us a lot , thank you!

**Comment by ggolcher** [comment]
Our baseline file is here: https://sketch.com/s/658126ee-2cd7-41c7-b95c-757b04edb3c1
You can always see every single screen and variation of the design there. We update it as we produce new screens always.

**Comment by kenshyx** [comment]
@ggolcher that doesn't help since it contains also screens from onboarding v2, I asked for exactly the screen that you are comparing to.

**Comment by ggolcher** [comment]
The login prompt screen was there: https://www.sketch.com/s/658126ee-2cd7-41c7-b95c-757b04edb3c1/a/4aOQkkx

**Comment by ggolcher** [comment]
And mobile: https://www.sketch.com/s/658126ee-2cd7-41c7-b95c-757b04edb3c1/a/4aOJn0z
