### ISSUE TITLE
Fix empty followers / following / interests content

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1372]
**Describe the bug**
Empty screen message does not match the design

**To Reproduce**
View a users without following, followed, and/or interests

**Expected behavior**
I expect to get the right message

**Device**
macOS 12.6, Chrome 94, MetaMask

**Screenshots**
![Screen Shot 2021-10-11 at 1 07 18 PM](https://user-images.githubusercontent.com/15471332/136838130-28c9731e-5135-4037-b2c8-1455cc104563.png)

**Comment by SeverS** [comment]
https://www.sketch.com/s/76d76643-a298-4a82-8492-3e28ef8d0c73
