### ISSUE TITLE
Replies in search not displaying as expected

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1374]
**Describe the bug**
Replies appear as a post entry and are non-clickable.

**To Reproduce**
Search for hello and click on the replies filter

**Expected behavior**
Replies should appear as replies and should be clickable

**Device**
macOS 12.6, Chrome 94, MetaMask

**Screenshots**
![Screen Shot 2021-10-11 at 1 11 32 PM](https://user-images.githubusercontent.com/15471332/136838758-442b5bde-d85c-482f-9b61-0cd59f7de2fd.png)

**Comment by quininez** [comment]
it is not clear what is meant by replies should appear as replies, in the sketch files we don't have replies on the search page, and the reply card right now is just like how they appear in the post page

**Comment by ggolcher** [comment]
I hear that, because I hadn't scope this in the design. There is no design for this.

I would prefer to go without replies, but if you insist in having it, I would include the original post in the results for replies so that the user can expand the post and see all replies. Just having the reply without context has little value.

**Comment by quininez** [comment]
Ok, that would mean bigger changes to the search page, and might be out of scope for the current release, maybe we can discuss this on the PXE call

**Comment by ggolcher** [comment]
OK

**Comment by ggolcher** [comment]
We'll leave as-is for now.
