### ISSUE TITLE
Sign in to a new address is not caught

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1375]
**Describe the bug**
If I try to sign in with an address that has no account, an undefined error is shown.

**To Reproduce**
Try to sign in using an account that does not have an account

**Expected behavior**
I should be shown the screen inviting me to Sign Up.

**Device**
macOS 12.6, Chrome 94, MetaMask

**Screenshots**
![Screen Shot 2021-10-11 at 1 14 05 PM](https://user-images.githubusercontent.com/15471332/136839208-9d13016b-4776-4e3e-a599-674980933fb3.png)

**Comment by ghost** [comment]
I am unable to reproduce this, sign-up modal shows up fine. Maybe somebody else can also try?
