### ISSUE TITLE
[Mobile] The "Edit Post" button is not appearing when the user tries to edit their post.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1382]
**Describe the bug**
Upon tapping the "Show more" button on their own posts, the user will prompted by a "Delete Post" and "Cancel" buttons but the "Edit Post" button is not appearing.

**To Reproduce**
1. Go to the "https://ethereum-world.netlify.app/social-app/feed" page.
2. Select one of your posts.
3. Tap the "Show more" button.

**Expected behavior**
The user should be prompted by an "Edit Post", "Delete Post", and "Cancel" buttons.

**Screenshots**

https://user-images.githubusercontent.com/79607355/136868161-98321642-fe23-4f88-a47e-e7d55eb24658.MP4

**Smartphone:**
iPhone X | OS 14.7.1
- FireFox Version 38.0 (6157)

HTC U12 +| OS 8
- Chrome version 94.0.4606.50

**Wallets Used:**
- MetaMask Web Extension and App

-AMLT

CC: @ggolcher

**Comment by ggolcher** [comment]
This was fixed
