### ISSUE TITLE
The "You reported this post for the following reason" text disappears when tapping the "See it anyway" button on a reported post on the Feed UI.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1385]
**Describe the bug**
When the user is on the Feed UI and taps the "See it anyway" button a reported post, the You reported this post for the following reason" report text disappears.

**To Reproduce**
1. Go to the "https://ethereum-world.netlify.app/social-app/feed" page.
2. Select a post that you reported.
3. Tap the "See it anyway" button.

**Expected behavior**
The "You reported this post for the following reason" text should still be displayed along with the post when tapping the "See it anyway" button.

**Video**

https://user-images.githubusercontent.com/79607355/136956967-52f13a5b-d7e4-497d-abf7-aa9dacabdac1.mp4

**Desktop:**
HP ProBook 4540s | Windows 10 Pro
- Google Chrome Version 94.0.4606.81

**Smartphone (please complete the following information):**
Samsung Galaxy A20 | OS 10 
- Google Chrome Version 94.0.4606.71

Wallet Used:
- MetaMask Web Extension 

-GKM

CC: @ggolcher

**Comment by SeverS** [comment]
That's a double click, first click will show the entry card and second will navigate to the post page.

**Comment by ggolcher** [comment]
That case is specifically in the design. If you report a post, then you should see a warning.

**Comment by ggolcher** [comment]
Check the design for the exact treatment and content.
