### ISSUE TITLE
Manually typed link doesn't show a preview and is not highlighted.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1390]
**Describe the bug**
When the user types a link on his post, the typed link will not become highlighted and the preview will not also be displayed.

**To Reproduce**
1. Go to the Social Feed.
2. Tap "Share your thoughts".
3. Manually type a link (e.g., https://ethereum-world.netlify.app).

**Expected behavior**
The link should become highlighted and a preview should also be displayed.

**Video and Logs**

https://user-images.githubusercontent.com/79607355/137064447-962a447d-8fa3-414d-bc7b-47829e1aa0b6.mp4
[iOS_log.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7341568/iOS_log.txt)

**Desktop:**

 Windows 10 Pro
 - Chrome | Version 94.0.4606.81

**Smartphone:**

iPhone XS |  iOS 14.1
 - Safari | 14
 

**Additional context**
- Issue does not occur when pasting a link.

**Wallet Used:**
MetaMask Web Extension and App

(JRG)

cc: @ggolcher

**Comment by ggolcher** [comment]
Why is this an enhancement? I see it as part of highlighting links.
