### ISSUE TITLE
View Post / Reply in Moderation History not working

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1399]
**Describe the bug**
View Post / Reply in moderation is missing, and a _Coming soon_ message displays.

**To Reproduce**
Go to Moderation History. Click to view a post or reply that has been kept.

**Expected behavior**
The post or reply should display.

**Screenshots**
![Screen Shot 2021-10-13 at 1 27 09 PM](https://user-images.githubusercontent.com/15471332/137195172-5325d73c-de29-4eb9-9bdc-9b5cfe103c4d.png)

**Platform**
Chrome, MetaMask

**Comment by ggolcher** [comment]
What happened with this?

**Comment by kenshyx** [comment]
We don't have a page dedicated for displaying a single `reply`, we've patched this to `redirect` now to the post where the reply belongs
