### ISSUE TITLE
Notifications and bookmarks show empty screens

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1400]
**Describe the bug**
Viewing notifications and bookmarks are outputting empty screens (sometimes)

**To Reproduce**
Tap the Notifications or Bookmarks button

**Expected behavior**
The user should see bookmarked posts and notifications.

**Screenshots**
![Screen Shot 2021-10-13 at 1 30 49 PM](https://user-images.githubusercontent.com/15471332/137195409-9863cece-f56f-4863-bba2-3011f601abd6.png)
![Screen Shot 2021-10-13 at 1 30 57 PM](https://user-images.githubusercontent.com/15471332/137195410-bd578246-6ea9-4995-a23c-66a57122a053.png)

**Platform**
Chrome, MetaMask

**Comment by SeverS** [comment]
did you had any bookmarked posts? I cannot reproduce this

**Comment by ggolcher** [comment]
Yes

**Comment by kenshyx** [comment]
this happened because you had bookmarked some posts from a different threadID, we've done a migration a couple of weeks ago
