### ISSUE TITLE
Subscriptions page is not full-screen on mobile

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1402]
**Describe the bug**
The subscriptions screen appears as a component over a white background.

**To Reproduce**
Go to subscriptions without a subscription.

**Expected behavior**
Subscriptions should be a full screen on mobile

**Screenshots**
![Screen Shot 2021-10-13 at 1 53 27 PM](https://user-images.githubusercontent.com/15471332/137195909-e84a6fd7-c42a-4cd6-a5ab-75f95eef627b.png)

**Platform**
Chrome, MetaMask

**Comment by SeverS** [comment]
Looks the same as
https://www.sketch.com/s/658126ee-2cd7-41c7-b95c-757b04edb3c1/a/Omb3Gj4

**Comment by ggolcher** [comment]
Holy shit! Snap, you are totally right!

That's our mistake then. May we fix it?
