### ISSUE TITLE
New post not full screen in mobile

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1403]
**Describe the bug**
Going to draft a new post in mobile shows an overlay, not the expected full screen experience. Also the margins shift weirdly.

**To Reproduce**
Draft a new post

**Expected behavior**
A full screen experience for new post should display.

**Screenshots**
![Screen Shot 2021-10-13 at 1 31 08 PM](https://user-images.githubusercontent.com/15471332/137196186-de16946d-377f-433e-88a4-76a3002da302.png)
![Screen Shot 2021-10-13 at 1 31 30 PM](https://user-images.githubusercontent.com/15471332/137196188-0aa4903d-3577-4618-aa53-f20e4aba8540.png)

**Platform**
Chrome, MetaMask

**Comment by ghost** [comment]
@ggolcher I'm pretty sure the keyboard would fill the missing space on a real device.

**Comment by SeverS** [comment]
@ggolcher how did you test this? From a real mobile device of emulated?

**Comment by quininez** [comment]
yes, the component shrinks on focus to leave space for the keyboard, so on a real device it should be ok

**Comment by ggolcher** [comment]
Actually, no cigar on a real device either. If we had a full screen experience as designed, we wouldn't have this problem. 

![Screenshot_20211014-070057](https://user-images.githubusercontent.com/15471332/137313686-8e4018e0-d2c0-42cd-a0b7-759562108443.png)

**Comment by quininez** [comment]
what does full screen experience mean in this case? in the designs I could find https://www.sketch.com/s/658126ee-2cd7-41c7-b95c-757b04edb3c1/a/Omb3p4m
and on my device it looks like ![IMG_8FC38ACA0540-1](https://user-images.githubusercontent.com/13240850/137319682-31923207-af62-467e-8084-10e13804b7d3.jpeg) on chrome/safari and like
![IMG_EBFD16C6CEC5-1](https://user-images.githubusercontent.com/13240850/137319812-ab56339a-311f-4632-925e-14e65232f4d8.jpeg)
on metamask browser. I can't tell why it behaves differently on metamask browser, maybe we need another approach to keep it consistent across browser. So would you say what I have on my device on chrome/safari is the full screen experience or is there something else involved?

**Comment by ggolcher** [comment]
On your device I can see very slight dark background lines, which suggests to me that it's just a large overlay.

**Comment by quininez** [comment]
Yes, it is an overlay, to keep consistency with the desktop app, where the editor is also loaded in an overlay. I think this was previously discussed but we can tackle it again in the PXE call.

**Comment by ggolcher** [comment]
OK!

**Comment by SeverS** [comment]
> Actually, no cigar on a real device either. If we had a full screen experience as designed, we wouldn't have this problem.
> 
@ggolcher What do you mean with "full screen experience"?

**Comment by ggolcher** [comment]
Have the post field take up the full screen as in the design
