### ISSUE TITLE
[Mobile] The "Delete Post" button is not appearing when the user tries to delete their post on the Honor Play OS 9 device with Private Firefox browser version of 93.1.0.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1404]
**Describe the bug**
Upon using a Private Firefox browser with a version of 93.1.0 on a Honor Play device with an OS of 9, tapping the "Show more" button on their own posts does not prompt the user with a "Delete" button.

**To Reproduce**
1. Login on a Private Firefox browser and go your Profile page.
2. Select one of your posts.
3. Tap the "Show more" button.

**Expected behavior**
The user should be prompted by an "Edit Post", "Delete Post", and "Cancel" options.

**Attachments**

https://user-images.githubusercontent.com/79607355/137226599-8adc9b6c-98a7-4534-bfbf-0410d3648b1e.mp4

[Android_Logcat_Missing_Delete_button_.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7341915/Android_Logcat_Missing_Delete_button_.txt)

**Smartphone:**
Honor Play | OS 9
 - Firefox Version 93.1.0

**Additional context**
- A "Report Post" button is appearing.
- The team also encountered the [1382](https://github.com/AKASHAorg/akasha-world-framework/issues/1382) ticket while reproducing this issue 

**Wallets Used:**
- MetaMask Web Extension and App.

-AMLT

CC: @ggolcher

**Comment by kenshyx** [comment]
Can you test it again please? We are not able to reproduce it.
