### ISSUE TITLE
The "Sorry, we can't fetch the followers list." error message is not appearing upon opening the "Followers/Following" modal while having a slow internet connection.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1405]
**Describe the bug**
When the user has a slow internet connection and opens their "Followers/Following" modal, the user will encounter a blank page and loading page and upon switching tabs an "Error in profile plugin" error message will appear.

**To Reproduce**
1. Go to the "https://ethereum-world.netlify.app/profile/my-profile" page.
2. Tap the "Followers" button.
3. Go to a different tab if there are no list that appears.

**Expected behavior**
Whenever the "Followers/Following" modal does not load quickly, the user should be prompted by a "Sorry, we can't fetch the followers list." error message.

**Attachments**

https://user-images.githubusercontent.com/79607355/137247815-734acefd-8f1f-4b21-b79a-8c39c1f8e462.MP4

[iOS_Logs_Error_in profile_plugin_error_message_appears.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7342851/iOS_Logs_Error_in.profile_plugin_error_message_appears.txt)

**Desktop:**
 Windows 10 Pro
 - Google Chrome 93.0.4577.82
 - Firefox92.0 (64-bit)

**Smartphone:**
Honor Play | OS 9
 - Chrome Version 94.0.4606.50
 - Firefox Version 93.1.0

iPhone X | OS 14.7.1
- FireFox Version 38.0 (6157)

HTC U12 +| OS 8
- Chrome version 94.0.4606.50

**Additional context**
- The "Error in profile plugin" error message will immediately appear on desktop browsers.

**Wallets Used:**
- MetaMask Web Extension and App

-AMLT

CC: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
