### ISSUE TITLE
The Reply Count does not decrease after deleting a reply from a post.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1407]
**Describe the bug**
When the user deletes his/her reply on a post, the Reply Count does not reduce after the reply was deleted.

**To Reproduce**
1. Go to the https://ethereum-world.netlify.app/social-app/feed website and login the user's account.
2. Tap the Reply button to any post.
3. Reply to the post and take note of the total amount of Replies.
4. Delete the Reply and check the total amount of Replies after the delete reply disappears.

**Expected behavior**
The Reply Count should be reduced after the deleted reply was removed.

**Attachments**
Video Attachment:
https://user-images.githubusercontent.com/79607355/137285530-6aeb9fd9-4e76-4296-80a9-af0464ef56d8.mp4
Android Logs:
[ReplyCountIsNotDecreaseing_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7344624/ReplyCountIsNotDecreaseing_AndroidLogs.txt)
iOS Logs: 
[ReplyCountIsNotDecreasing_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7344627/ReplyCountIsNotDecreasing_iOSLogs.txt)

**Desktop (please complete the following information):**
 - Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
    - Safari Version 14.1.2
    - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - B550 Aourus Elite | Windows 10 Pro
    - Firefox Version 90.0.2 (64-bit)
    - Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Google Pixel 4a | OS 12 Beta 4
    - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - iPhone X | OS 14.7.1
    - MetaMask Version v3.4.1 (785)

**Additional context**
- The team also tried to reload the website but the Reply Count did not decrease

EP (AAP)

CC: @ggolcher

**Comment by kenshyx** [comment]
the counter updates after 6s
