### ISSUE TITLE
The "Publish" button is active and can be tapped while uploading a photo for a status update.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1408]
Describe the Bug:
When uploading a picture, the "Publish" button is not on a down state and can be clicked while a photo is in progress of being uploaded.

To Reproduce:
1. Go to "https://ethereum-world.netlify.app/social-app/feed".
2. Tap/Click the "Share your thoughts" section to make a post.
3. Tap/Click the upload icon to select a picture to upload.
4. Tap/Click the publish button while the picture to be uploaded is still in progress.

Expected Behavior.
The "Publish" button should be disabled while a picture upload is still in progress.

https://user-images.githubusercontent.com/79607355/137324331-456dfa1e-c29d-453e-8a54-8e2025b462f2.mp4

Desktop:
B550 Aourus Elite Windows 10 Pro
Chrome Version 94.0.4606.81 (Official Build) (64-bit)

B550 Aourus Elite Windows 10 Pro Windows Firefox 
Version 90.0.2 (64-bit)

MetaMask Version: 10.2.2

@ggolcher 
(AAV)

**Comment by ggolcher** [comment]
Verified fixed
