### ISSUE TITLE
The "upload a photo" button does not allow multiple photos to be uploaded all at once.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1409]
Describe the Bug:
When uploading a photo the "upload a photo" button does not let user select multiple photos to be uploaded all at once.

To Reproduce.
1.Go to "https://ethereum-world.netlify.app/social-app/feed".
2.Tap/Click the "Share your thoughts" section to make a post.
3.Tap/Click the "upload a photo" icon to select multiple photos to upload.

Expected Behavior.
The user should be able to select multiple photos to upload.

https://user-images.githubusercontent.com/79607355/137326189-3dc94efb-aab3-413c-8080-f3119f39156e.mp4

Desktop:
B550 Aourus Elite Windows 10 Pro
Chrome Version 94.0.4606.81 (Official Build) (64-bit)

B550 Aourus Elite Windows 10 Pro Windows Firefox 
Version 90.0.2 (64-bit)

MetaMask Version: 10.2.2

@ggolcher 
(AAV)

**Comment by SeverS** [comment]
We don't have this feature yet.
