### ISSUE TITLE
The Moderation History graph does not display the proper percentage for each data entry.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1410]
Describe the Bug:
When the user views the Moderation History graph, the displayed circle does not show the percentage for each data entry present.

To Reproduce.
1. Go to "https://ethereum-world.netlify.app/social-app/feed".
2. Click the Moderation History.
3. Observe the Moderation History graph.

Expected Behavior.
The Moderation History graph should display in percentage every data entry that is present.
![Data percentage missing](https://user-images.githubusercontent.com/79607355/137329011-f801b1ec-1bae-4337-b47c-5a52d44492b8.PNG)

Desktop:
B550 Aourus Elite Windows 10 Pro
Chrome Version 94.0.4606.81 (Official Build) (64-bit)

B550 Aourus Elite Windows 10 Pro Windows Firefox 
Version 90.0.2 (64-bit)

MetaMask Version: 10.2.2

@ggolcher 

(AAV)

**Comment by kenshyx** [comment]
the total number is an aggregated value
