### ISSUE TITLE
The Search field does nothing when the user enters an invalid text.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1411]
Describe the Bug:
The user does not get a "Please enter a valid text" when typing a blank (Space) on the search field.

To Reproduce.
1. Go to "https://ethereum-world.netlify.app/social-app/feed".
2. Click the Search field and press "spacebar".
3. Click the search button after pressing "spacebar".

Expected Behavior.
The user should be prompted any message regarding entering invalid texts.

https://user-images.githubusercontent.com/79607355/137331555-2663697f-4c01-4c02-9483-88c4de04a7ce.mp4

Desktop:
B550 Aourus Elite Windows 10 Pro
Chrome Version 94.0.4606.81 (Official Build) (64-bit)

B550 Aourus Elite Windows 10 Pro Windows Firefox 
Version 90.0.2 (64-bit)

MetaMask Version: 10.2.2

@ggolcher 
(AAV)

**Comment by ghost** [comment]
@ggolcher I think it's up to UX to decide if we need a message in this case, some do it (ebay, duckduckgo) while others don't (youtube, google, amazon).

**Comment by ggolcher** [comment]
I don't think we need the message. It's too much of an edge case.
