### ISSUE TITLE
[Desktop] Hovering the cursor above the Post, Followers, Following and Interest texts in the Profile page does not highlight the whole text button.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1412]
**Describe the bug**
When the user is on his/her Profile page or another user's Profile page and highlights the Post, Followers, Following and Interest texts, the icon and the number of the Post, Followers, Following and Interest will not be included in the highlight.

**To Reproduce**
1. Go to the https://ethereum-world.netlify.app/social-app/feed website
2. Enter the user's Profile page or another user's Profile page.
3. Highlight one of the following:
   - Post
   - Followers
   - Following 
   - Interest
4. Check the highlight of the text button.

**Expected behavior**
The icon and the number of the Post, Followers, Following and Interest should be included in the highlight when the user hovers his/her cursor on them.

**Screenshots**
Video attachment: 
https://user-images.githubusercontent.com/79607355/137330360-f89822a1-36ec-46e6-b2f2-e31a39ae1c66.mp4
Screenshot attachment:
![PostTextButtonHighlightIssue](https://user-images.githubusercontent.com/79607355/137328898-571a5e3a-0271-4daa-9eea-fa661d3d2444.png)

**Desktop (please complete the following information):**
 - Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
    - Safari Version 14.1.2
    - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - B550 Aourus Elite | Windows 10 Pro
    - Firefox Version 90.0.2 (64-bit)
    - Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Additional context**
- The issue does not occur when hovering the cursor on the icon or number of the Post, Followers, Following and Interest text buttons.

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
