### ISSUE TITLE
The 'Replies' button is unresponsive upon tapping on the pending UI of the Moderator Dashboard.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1413]
**Describe the bug**
Upon tapping the 'Replies' button on the pending UI of the Moderator Dashboard, the button is unresponsive.

**To Reproduce**
1. Open any browser (ex: Firefox).
2. Go to the 'https://ethereum-world.netlify.app/moderation-app/home' webpage and then log in to the metamask account.
3. Look for a reported post with 2 or more replies.
4. Tap the 'Replies' button

**Expected behavior**
The button is unresponsive.

**Attachments**

https://user-images.githubusercontent.com/79607355/137427936-e24b43d1-51b1-4181-8f91-5aee1346ea44.mp4

[Replies_Unresponsive.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7350688/Replies_Unresponsive.txt)

**Desktop (please complete the following information):**
Dell Optiplex 3040 | Windows 10 Pro
-Firefox Version 92.0.1
Asus FX553VD | Windows 10 Pro
-Chrome Version 94.0.4606.81

**Smartphone (please complete the following information):**
Honor Play | 9
-Firefox Version 93.1.0
iPad Pro 12.9 inch | 15.0.2
-Safari 15.0.2
iPad 9.7 (5th Gen) | 13.6
-Firefox Version 38.1 (6216)

**Additional context**

**Wallet Used:**
MetaMask Web Extension and App

(NJPDR)

cc:@ggolcher

**Comment by ggolcher** [comment]
This is acceptable as-is.
