### ISSUE TITLE
An error message "Upload failed" appears when the user uploads an image upon publishing a post using an iOS device.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1415]
**Describe the bug**
When the user uploads an image when publishing a post using an iOS device, the user encounters an error message "Upload failed".

**To Reproduce**
1. Open the social app feed: https://ethereum-world.netlify.app/social-app/feed.
2. Tap on the "Share your thoughts" field.
3. Tap the image button on the New Post modal.
4. Select the location of the image to be uploaded and select the image.
5. Observe the New Post modal.

**Expected behavior**
- The user should be able to upload an image when publishing a post.

**Screenshots**

https://user-images.githubusercontent.com/79607355/137430160-f18569d9-e611-4d50-9957-b7c411d386a6.mp4

[UploadFailedWhenUploadingAnImage.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7350779/UploadFailedWhenUploadingAnImage.txt)

**Smartphone (please complete the following information):**
- iPhone XS | 14.1
-Safari 14
- iPad Pro 12.9 inch | 15.0.2
-Safari 15.0.2
-Chrome Browser Version 94.4606.76
-Firefox Browser Version 38.1
-MetaMask Browser Version 3.4.1

**Additional context**
- The issue also occurs when the user selects the "Take a Photo or Video" option when uploading an image.

Wallets Used:

- MetaMask App

(JKF)

CC: @ggolcher

**Comment by ggolcher** [comment]
This is important to launch.

**Comment by kenshyx** [comment]
this is related to the issue I've described during the call from yesterday, it's not something we can fix, the patch must be applied on the textile nginx configuration
