### ISSUE TITLE
[Desktop] The cursor appears at the leftmost side when editing the user's reply.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1416]
**Describe the bug**
When the user tries to edit his/her reply,  the cursor appear at the leftmost side of the Reply Textbox.

**Pre-Requisite**
1. User should be login to https://ethereum-world.netlify.app/social-app/feed

**To Reproduce**
1. Tap the Reply button to any Post.
2. Add a new Reply.
3. Tap the Reply's Menu button and click the Edit Reply.
4. Check the location of the user's cursor.

**Expected behavior**
The user's cursor should appear at the rightmost side when he/she tries to edit his/her reply. 

**Attachment**
Video Attachment:
https://user-images.githubusercontent.com/79607355/137446536-ab0c7926-cb10-4875-aef7-162f60e4db76.mp4

**Desktop:**
 - Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
   - Safari Version 14.1.2
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
- The issue does not occur when editing the user's Post (the cursor does not appear)

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
@kenshyx I don't see this as an enhancement. We should simply show the cursor at the end of the text content.

We should address this before launch.
