### ISSUE TITLE
The Posts and Replies' creation and last edited time does not update real time.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1418]
**Describe the bug**
After the user created or edited a Post or a Reply, the Post/Reply's creation or last edited time does not update realtime.

**To Reproduce**
Post Creation/Edit: 
1. On the Main page, tap the Share Your Thoughts text box.
2. Enter any text and tap the Publish button.
3. Wait for a few minutes and check the Post's Creation Time.
4. Tap the post's Menu.
5. Tap the Edit Post button and edit the post.
6. Tap the Save Changes button.
7. Wait for a few minutes and tap the Edit Icon on the post.

Reply Creation/Edit: 
1. On the Main page, tap the Reply button on any post.
2. Enter any text on the Reply to text box and tap the Reply button.
3. Wait for a few minutes and check the Reply's Creation Time.
4. Tap the Reply's Menu.
5. Tap the Edit Reply button and edit the reply.
6. Tap the Reply button.
7. Wait for a few minutes and tap the Edit Icon on the reply.

**Expected behavior**
The Post/Reply's creation or last edited time does not update realtime after the user creates or edit his/her Post or Reply.

**Attachments**
Video Attachment:
Post's Creation Time:
https://user-images.githubusercontent.com/79607355/137470564-d96d1b9b-e32b-4bef-8dc8-d4f1e469d576.mp4
Post's Last Edited Time:
https://user-images.githubusercontent.com/79607355/137470580-5222d2bd-6ff2-40fb-9f62-dd39b57fde19.mp4
Reply's Creation Time:
https://user-images.githubusercontent.com/79607355/137470592-c1238e58-f6f3-429d-9eb7-0b70195410fb.mp4
Reply's Last Edited Time:
https://user-images.githubusercontent.com/79607355/137470604-69a0a943-4170-48d7-a208-226b9959d1ba.mp4

**Logs:**
Post's Creation Time:
[Post'sCreationTimeDoesNotUpdateRealtime_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7352636/Post.sCreationTimeDoesNotUpdateRealtime_AndroidLogs.txt)
[Post'sCreationTimeDoesNotUpdateRealtime_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7352637/Post.sCreationTimeDoesNotUpdateRealtime_iOSLogs.txt)
Reply's Creation Time:
[Reply'sCreationTimeDoesNotUpdateRealtime_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7352639/Reply.sCreationTimeDoesNotUpdateRealtime_AndroidLogs.txt)
[Reply'sCreationTimeDoesNotUpdateRealtime_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7352640/Reply.sCreationTimeDoesNotUpdateRealtime_iOSLogs.txt)

**Desktop:**
 - Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
   - Safari Version 14.1.2
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Smartphone:**
 - Samsung Galaxy S9 | OS 10
    - Chrome 86.0.4240.198
 - Google Pixel 4a | OS 12 Beta 4
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - iPhone X | OS 14.7.1
   - Chrome Version 94.0.4606.52

**Additional context**
- The team was unable to test the Post and Reply's Last Edited time issue on Mobile Devices due to the Edit button does not appear when the user tries to edit a Post or a Reply.

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
