### ISSUE TITLE
[Desktop] The text on the Save button is displayed as "Reply" when editing a reply on a Post.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1420]
**Describe the bug**
When the user edits a reply on the post, the text on the Save button is still displayed as "Reply" instead of "Save".

**To Reproduce**
1. On the main page, click on the Reply button on any post.
2. Enter any text on the reply to text box and click the Reply button.
3. Click the 3 dots on the user's reply and edit it.
4. Check the text displayed on the Save button.

**Expected behavior**
- The text on the Save button should be displayed as "**Save**" when editing a reply on a Post.

**Screenshots**

![Save Button_Reply Button_sc](https://user-images.githubusercontent.com/79607355/137480146-cb6aeacc-180c-442b-9633-a07de18463db.png)

**Desktop:**
- Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
-- Safari Version 14.1.2
-- Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
- The team was unable to test the edit reply feature on Mobile Devices due to the Edit button does not appear when the user tries to edit a Post or a reply https://github.com/AKASHAorg/akasha-world-framework/issues/1309.

EP (MMB)

CC: @ggolcher

**Comment by ggolcher** [comment]
We need to fix this before launch.

**Comment by quininez** [comment]
ready for review on staging

**Comment by ggolcher** [comment]
Looks good!
