### ISSUE TITLE
The Reason for the Report does not appear after tapping the "See it anyway" text button on a post or reply.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1422]
**Describe the bug**
When the user reports a post or a reply and taps the "See it anyway" text button, the Reason for the Report does not appear.

**Pre-Requisite**
1. User should be login to https://ethereum-world.netlify.app/social-app/feed

**To Reproduce**
1. Tap the Menu on a post or a reply.
2. Report the post or reply.
3. Tap the "See it anyway" text button.
4. Check the post or reply.

**Expected behavior**
The Reason for the Report should still appear on the post or reply when tapping the "See it anyway" text button.

**Attachments**
Video Attachments:
Post's Reason for the Report: 
https://user-images.githubusercontent.com/79607355/137483001-99d3a964-866c-4f0f-9df9-2feadb66fe49.mp4
Reply's Reason for the Report:
https://user-images.githubusercontent.com/79607355/137483012-36d9dd8c-05b9-4e13-ae14-cf81558693cb.mp4

Logs:
[ReplyReportReasonIssue_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353207/ReplyReportReasonIssue_AndroidLogs.txt)
[PostReportReasonIssue_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353210/PostReportReasonIssue_AndroidLogs.txt)
[PostReportReasonIssue_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353213/PostReportReasonIssue_iOSLogs.txt)

**Desktop:**
- Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
   - Safari Version 14.1.2
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Smartphone:**
 - Samsung Galaxy S9 | OS 10
    - Chrome 86.0.4240.198
 - Google Pixel 4a | OS 12 Beta 4
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - iPhone X | OS 14.7.1
   - Chrome Version 94.0.4606.52

**Additional context**
Reference from Sketch:
Post: https://www.sketch.com/s/ce41392a-178d-48d7-9531-57bc5a884b84/a/YGvgZQd
Reply: https://www.sketch.com/s/ce41392a-178d-48d7-9531-57bc5a884b84/a/zxb40jb

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
