### ISSUE TITLE
The suspended user can still post and reply to other posts.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1424]
**Describe the bug**
When a user's account is suspended by being reported by another user, the suspended user can still post and reply on other posts.

**Pre-Requisite**
1. User should be login to https://ethereum-world.netlify.app/social-app/feed
2. The user should be suspended.

**To Reproduce**
1. On the Main page, tap the Share Your Thoughts text box
2. Enter any text and tap the Publish button.
3. Check if the created post will be posted
4. On the Main page, tap the Reply button on any post.
5. Tap the Reply to text box and enter any text.
6. Tap the Reply button and check if the Reply will be added.

**Expected behavior**
The user should be automatically logged-out or should not be able to login when his/her account is suspended.

**Attachments**
Video Attachments:
Post: https://user-images.githubusercontent.com/79607355/137498014-ef148b28-342e-4e12-843d-ec69ea9e346e.mp4
Reply: https://user-images.githubusercontent.com/79607355/137498063-63705a41-ce40-48b8-9fa5-4a45f5aa4c7f.mp4

Logs:
Post:
[SuspendedUserCanStillPost_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353820/SuspendedUserCanStillPost_iOSLogs.txt)
[SuspendedUserCanStillPost_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353821/SuspendedUserCanStillPost_AndroidLogs.txt)
Reply:
[SuspendedUserCanStillReply_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353841/SuspendedUserCanStillReply_AndroidLogs.txt)
[SuspendedUserCanStillReply_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7353843/SuspendedUserCanStillReply_iOSLogs.txt)

**Desktop (please complete the following information):**
 - Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
   - Safari Version 14.1.2
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Samsung Galaxy S9 | OS 10
    - Chrome 86.0.4240.198
 - Google Pixel 4a | OS 12 Beta 4
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - iPhone X | OS 14.7.1
   - Chrome Version 94.0.4606.52

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
We should absolutely fix this before launch.
