### ISSUE TITLE
The 'Back' button of Android Devices is not working on the webpage of Ethereum World when using a Metamask browser.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1427]
**Describe the bug**
Upon visiting the Ethereum World web while using a Metamask browser, the Android device's back button is not working on the UI's when tapping.

**To Reproduce**
1. Open the Metamask app.
2. Tap the hamburger menu.
3. Tap the browser button.
2. Go to the 'https://ethereum-world.netlify.app/social-app/feed' webpage and then log in to the Metamask account.
3. Tap any UI. (ex, Share your thoughts)
4. Minimize the keyboard.
5. Tap the Android device's back button.

**Expected behavior**
The user should be redirected to the previous page or UI.

**Attachments**

https://user-images.githubusercontent.com/79607355/137561910-b85c4278-613a-4326-b238-072681b505ea.mp4

[BackButton_NotWorking_MetamaskBrowser.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7356276/BackButton_NotWorking_MetamaskBrowser.txt)

**Smartphone (please complete the following information):**
HTC U12+ | 8
-MetaMask Version v3.4.1 (785)
Honor Play | 9
-MetaMask Version v3.4.1 (785)

**Additional context**

**Wallet Used:**
MetaMask Web App

(NJPDR)

cc:@ggolcher

**Comment by ghost** [comment]
This is a bug in Metamask itself, not Ethereum World. It has been reported on Metamask github repo https://github.com/MetaMask/metamask-mobile/issues/3307 .
