### ISSUE TITLE
The "Legal and Policies" on the Meatballs menu is missing the "and Policies" part.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1428]
**Describe the bug**
While no account is signed in yet and viewing the Meatballs menu, the "Legal and Policies" part is missing the "and Policies".

**To Reproduce**
1. Access the Meatballs menu.
2. Check the "Legal and Policies" part.

**Expected behavior**
The "Legal and Policies" phrase should be complete.

**Screenshots**
![SketchReference](https://user-images.githubusercontent.com/79607355/137564031-e967ffa3-61fa-45cb-a215-ef501abed458.png)
![MissingAndPolicies](https://user-images.githubusercontent.com/79607355/137564033-5fc33b42-c277-44d3-a7e2-c0541b3e979a.jpg)

**Smartphone (please complete the following information):**
- iPhone Pro | OS: 14.1
- Google Chrome Version 94.0.4606.76
- HTC U12+ | OS: 8
- MetaMask Version v3.4.1 (785)

Wallet Used:
MetaMask Web App

(NGR)

cc:@ggolcher

**Comment by ggolcher** [comment]
@kenshyx We need to change copy in the label.

We should fix this before launch since it's small.

**Comment by kenshyx** [comment]
@ggolcher we followed the design file https://www.sketch.com/s/658126ee-2cd7-41c7-b95c-757b04edb3c1/a/25eJ9n1

**Comment by ggolcher** [comment]
Well you are right! Apologies!
