### ISSUE TITLE
The Settings option is missing on the Profile menu.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1429]
**Describe the bug**
While there is an account logged in, the Settings option is missing on the Meatballs menu.

**To Reproduce**
1. Log in to an account.
2. Access the Profile menu.
3. Check the list of options.

**Expected behavior**
The Settings option should be available.

**Screenshots**
Reference:
![Sketch Reference](https://user-images.githubusercontent.com/79607355/137567457-d436b17a-240c-4b1a-b720-6571b89b2e9a.png)
![MissingSettingsOption](https://user-images.githubusercontent.com/79607355/137567455-a882cbb9-6e66-4173-a9bb-34679f65db35.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Dell Optiplex 3040
 - Edge Version 94.0.992.47

**Smartphone (please complete the following information):**

Wallet Used:
MetaMask Web App

(NGR)

cc:@ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch

**Comment by ggolcher** [comment]
No settings yet
