### ISSUE TITLE
[Desktop] The Filters on the Moderation History Page disappears when the user selects a moderated item.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1431]
**Describe the bug**
When clicking on any of the listed moderated items on the Moderation History Page, the Filters (All, Kept, Delisted) disappears.

**To Reproduce**
1. Navigate to the Moderation History Page. 
2. Check the Filters displayed.
3. Select any moderated item.
4. Check for the Filters displayed.

**Expected behavior**
The Filters should remain displayed when selecting a moderated item on the Moderation History Page.

**Video attachment**

https://user-images.githubusercontent.com/79607355/137576182-6763758f-a4e4-470c-a7bb-7b83b39f537a.mp4

**Desktop (please complete the following information):**
 

- Desktop | Windows 10 Pro
-- Chrome Version 94.0.4606.71
-- Firefox Version 93.0
- Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
-- Safari Version 14.1.2
-- Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
- The Filters are displayed again when the user reloads the site.

EP (MMB)

cc:@ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
