### ISSUE TITLE
[Mobile] The user is redirected to a different UI when tapping the Device's Back button while on a Moderated Item Details UI.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1432]
**Describe the bug**
When tapping the Back button of the Device while on the Moderated Item Details UI, the user being redirected to a different UI instead of the Moderation History List UI.

**To Reproduce**
1. Navigate to the Moderation History UI.
2. Tap any of the moderated items on the list.
3. Tap the Device's Back button.
4. Check the UI where the user is redirected.

**Expected behavior**
The user should be redirected to the Moderation History UI when tapping the Device's Back button while on a Moderated Item Details UI.

**Video attachment**

https://user-images.githubusercontent.com/79607355/137577219-a2835298-e719-45a7-b9d0-1a890d74fea4.mp4

**Logs attachments**

[Back button_issue_Androidddms.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7357081/Back.button_issue_Androidddms.txt)
[Back button_issue_iOSlogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7357082/Back.button_issue_iOSlogs.txt)

**Smartphone:**
- Samsung Galaxy S9 | 10
-- Chrome 86.0.4240.198
-- Firefox Version 93.1.0
- iPhone X | OS 14.7.1
-- Chrome Version 94.0.4606.52

EP (MMB)

cc:@ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
