### ISSUE TITLE
The Show More option does not appear when there are 4 or more report entries in the reported post or reply.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1433]
**Describe the bug**
When the user views the explanation of a reported post or reply in the Pending or Moderated tab of the Moderation app, the Show More option does not appear even though there are 4 or more report entries in it.

**Pre-requisites;**
1. The user should be logged in to the https://ethereum-world.netlify.app/moderation-app.
2. There should be a post or reply that has 4 or more report entries.

**To Reproduce**
1. On the reported post or reply, tap the Show Explanations button.
2. Check the expanded entries.

**Expected behavior**
-  The limit of the initial shown entries should be set to 3 and there should be a Show More option below it. 
    - Please see the Additional Context section for the reference.

**Attachments**
Video Attachment:
https://user-images.githubusercontent.com/79607355/137578566-ffa2bc88-b7ca-4ab2-8ef9-2ba69c676c7f.mp4
Screenshot Attachment:
![TheSeeMoreOptionDoesNotAppear](https://user-images.githubusercontent.com/79607355/137578526-8e8bfb8d-88d6-49a1-bf50-e456ed729f65.PNG)
Logs:
[TheShowMoreOptionDoesNotAppear_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7357141/TheShowMoreOptionDoesNotAppear_iOSLogs.txt)
[TheShowMoreOptionDoesNotAppear_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7357142/TheShowMoreOptionDoesNotAppear_AndroidLogs.txt)

**Desktop:**
- Desktop | Windows 10 Pro
  - Chrome Version 94.0.4606.71
  - Firefox Version 93.0
- Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
  - Safari Version 14.1.2
  - Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Smartphone:**
- Samsung Galaxy S9 | OS 10
  - Chrome 86.0.4240.198
- iPhone X | OS 14.7.1
  - Chrome Version 94.0.4606.52

**Additional context**
Show More option Sketch reference link: https://www.sketch.com/s/110a2ab5-bc9b-43c6-9b14-7f388872f31f/a/dyewPm

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
