### ISSUE TITLE
The Menu is not closing after tapping the Moderator Dashboard when using a Moderator account.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1434]
**Describe the bug**
When the user is using a Moderator account and tries to enter the Moderator Dashboard via the Menu, the Menu will not close after the user taps the Moderator Dashboard button.

**Pre-requisites:**
1. The user should be logged in to the https://ethereum-world.netlify.app/social-app/feed.
2. The user should be using a Moderator account.

**To Reproduce**
1. On the Main page, tap the Menu button.
2. Tap the Moderator Dashboard button.

**Expected behavior**
The Menu should automatically close after the user taps the Moderator Dashboard button.

**Attachments**
Video Attachments:
https://user-images.githubusercontent.com/79607355/137581430-59a872a9-8e71-425e-90f1-0217c40600f3.mp4
Logs:
[TheMenuDoesNotClose_iOSLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7357266/TheMenuDoesNotClose_iOSLogs.txt)
[TheMenuDoesNotClose_AndroidLogs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7357267/TheMenuDoesNotClose_AndroidLogs.txt)

**Desktop:**
- Desktop | Windows 10 Pro
  - Chrome Version 94.0.4606.71
  - Firefox Version 93.0
- Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
  - Safari Version 14.1.2
  - Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Smartphone:**
- Samsung Galaxy S9 | OS 10
  - Chrome 86.0.4240.198
- iPhone X | OS 14.7.1
  - Chrome Version 94.0.4606.52
  - Metamask Browser Version v3.4.1 (785)

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
This is not a blocker to launch
