### ISSUE TITLE
Clicking a notification for a past post with a reply auto refreshes the page.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1436]
Describe the bug:
When the user clicks the notification for a past post with a reply from previous days, the page auto refreshes.

To Reproduce
1. Log in to "https://ethereum-world.netlify.app/moderation-app/history"
2. Go to the notifications.
3. Click any past post with a reply.

Expected behavior
The page should redirect the user to the post.

https://user-images.githubusercontent.com/79607355/137613710-97736cc1-5e40-4079-b8c1-88e5015f92b5.mp4

Desktop:
Windows 10 Pro | Mozilla Firefox 93.0 (64-bit)

Smartphone:
Google Pixel 4a | 12 Beta 4
iPhone X | 14.7.1

(AAV)

cc @ggolcher

**Comment by quininez** [comment]
Currently clicking on the empty space/blue dot marks the notification as read, and clicking on the text redirects to the post/profile/reply. It was refreshing the page when marking as read, creating that weird UI behaviour. I fixed this and now it keeps the notifications in view while updating the state.
What should the behaviour be for clicking on the empty space between the notification text and the blue dot? Should it mark as read, redirect to the notification's origin or do nothing? @ggolcher

**Comment by ggolcher** [comment]
Only marking the blue dot should mark the notification as seen without viewing the post/reply. Anywhere else in the row should take the user to the post/reply.

**Comment by ggolcher** [comment]
We should fix this before launch.

**Comment by quininez** [comment]
this is ready for review on staging

**Comment by ggolcher** [comment]
Looks perfect!
