### ISSUE TITLE
The Post or Account that was viewed via the Moderated tab does not have a back button to return the user back to the Kept Post or Account's entry.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1437]
**Describe the bug**
When the user taps the View Post or View Account in the Kept Post or Account's entry on the Moderated tab, the back button for the user to use to return to the Kept Post or Account's entry does not appear.

**Pre-requisites:**
1. The user should be logged in the https://ethereum-world.netlify.app/moderation-app 
2. There should be a Kept Account or Post in the Moderated tab.

**To Reproduce**
1. On the Moderator tab, tap the entry of a Kept Post or Account.
2. Tap the View Post or View Account text button.
3. Check the viewed Post or Account page.

**Expected behavior**
There should be a back button that the user can use to return to the Kept Post or Account's entry in the Moderated tab

**Attachments**
Video Attachment
https://user-images.githubusercontent.com/79607355/137624435-15b9069c-3219-4143-b410-21c81f0ad8dd.mp4

**Desktop:**
- Apple iMac (21.5 Inch 2017)| macOS Big Sur Version 11.5.2	
   - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
- B550 Aorus Elite | Windows 10 Pro
   - Firefox Version 93.0 (64-bit)

**Smartphone:**
- iPhone X | OS 14.7.1
   - Firefox Version 38.1 (6216)
- Google Pixel 4a | OS 12 Beta 4
   - Chrome Version 94.0.4606.85
   - Firefox Version 93.1.0

**Additional context**
- The team can still return to the Kept Post or Account's entry by tapping the back button on the browser.

EP (AAP)

CC: @ggolcher

**Comment by ggolcher** [comment]
@kenshyx, what additional information do you need? It seems self-explanatory to me. If you view a post from mod history, and then press back to return to mod history, the back button won't work as expected. 

This is not a blocker to launch
