### ISSUE TITLE
Usability issue with long profile names

### ISSUE THREAD

**Issue by mcimiotta** [AKASHAorg/akasha-world-framework#1438]
**Describe the bug**
Unusable modal with long profile name

**To Reproduce**
1. Go to profile and edit it
2. Add a long profile name and save
3. Click any of the following profile buttons "Followers / Following / Topics" to open the modal details
4. The user cannot close the modal clicking the "x" button or by typing "ESC"

**Expected behavior**
The user navigation shouldn't be blocked 

**Screenshots**
![image](https://user-images.githubusercontent.com/4280057/137916651-9c193c1e-1227-47ba-a668-bdbab7f7106e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 94

**Comment by ggolcher** [comment]
This is not a blocker to launch

**Comment by quininez** [comment]
ready for review on staging

**Comment by ggolcher** [comment]
Looks good!
