### ISSUE TITLE
Insert emoji after image upload doesn't work

### ISSUE THREAD

**Issue by quininez** [AKASHAorg/akasha-world-framework#1439]
**Describe the bug**
After uploading an image in the editor the user cannot insert emojis.

**Expected behavior**
The user should be able to insert emojis at all times.

**Desktop (please complete the following information):**
 - OS: all versions
 - Browser: all browsers
 

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all

**Additional context**

**Comment by ggolcher** [comment]
We should fix this before launch

**Comment by ggolcher** [comment]
Works very well!
