### ISSUE TITLE
Picture expected to be in portrait mode, no landscape mode

### ISSUE THREAD

**Issue by mcimiotta** [AKASHAorg/akasha-world-framework#1440]
**Describe the bug**
I created a post with a picture shot in portrait mode from my mobile. Instead of keeping this mode, the picture has been published in landscape mode.

**To Reproduce**
1. Edit a post with a picture shot in portrait mode
2. The picture is uploaded in landscape mode

**Expected behavior**
As a user I expect to upload the picture as it's been taken.

**Screenshots**
![image](https://user-images.githubusercontent.com/4280057/137937472-47fbb17d-1153-4a6a-bfb2-8aa78b62f392.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 11
 - Browser: Metamask browser
 - Version 3.3.0

**Additional context**

**Comment by ggolcher** [comment]
This is not a blocker to launch

**Comment by SeverS** [comment]
@mcimiotta can you post this image here? I suspect is in portrait mode but it just gets cropped
