### ISSUE TITLE
Wrong visual pop up when reposting from Twitter

### ISSUE THREAD

**Issue by Bugger78** [AKASHAorg/akasha-world-framework#1446]
**Describe the bug**
I can't save a post

**To Reproduce**
1. Go to 'Twitter' and copy a link to the tweet 
2. Go to Ethereum World and post this link 
3. The visual content that pops up shows the profile title and not the specific post visual

**Expected behavior**
When I repost a tweet I expect to see in the pop up the visual related to the post.

**Screenshots**
![image](https://user-images.githubusercontent.com/82663162/138168942-97f85b51-c19e-4a0d-9ac3-35cd5ea0e97a.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Firefox 
 - Version 93.0
![Meme](https://user-images.githubusercontent.com/82663162/138169231-0ec38738-5fad-4df2-aecd-1499a24fd2b6.jpeg)

**Comment by SeverS** [comment]
You can't get a visual related to a particular post on twitter if you only pasted twitter.com/EthereumMemes. You wanted to paste twitter.com/EthereumMemes/status/`somestatusid` (the link to the actual post).
