### ISSUE TITLE
Tooltip does not render the right size

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1451]
The tooltip in Notifications does not stretch to fit the text.
![Screen Shot 2021-10-21 at 4 43 39 PM](https://user-images.githubusercontent.com/15471332/138361260-91a5e274-1761-46cb-8abc-7fe01dbc7563.png)

Chrome, macOS

**Comment by ghost** [comment]
fixed by #1430 , this was probably loaded from cache, can you check again?

**Comment by ggolcher** [comment]
Looks good!
