### ISSUE TITLE
[Android] The texts on the Report Post/Reply modal overlap with each other when the virtual keyboard is displayed.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1453]
**Describe the bug**
When the user reports a Post or a Reply, opening the virtual keyboard by tapping the Explanation Field will cause the texts to overlap.

**To Reproduce**
1. On the Social Feed page, tap any profile available.
2. Tap the 3 dot menu then tap the Report button.
3. Open the virtual keyboard by tapping the Explanation Field.
4. Check the texts on the modal.

**Expected behavior**
The texts on the Report Post/Report modal should not overlap when the user opens the virtual keyboard.

**Attachments**
Screenshot Attachment
![Overlapping texts_sc](https://user-images.githubusercontent.com/79607355/138457361-7f808381-96d4-4a45-bda5-e6c4b39396b9.png)

**Smartphone (please complete the following information):**
- Samsung Galaxy S9 | OS 10
  - Chrome Version 86.0.4240.198
  - Firefox Version 93.1.0
- Google Pixel 4a | OS 12 Beta 4	
  - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
- Samsung Galaxy Note 8 | OS 7.1.1
  - Chrome Version 93.0.3577.82

**Additional context**
The issue is not occurring when using iOS devices.

EP (AAP)

CC: @ggolcher

**Comment by ghost** [comment]
This was fixed by #1444 , was probably loaded from metamask cache, closing
