### ISSUE TITLE
The menu button on both post and reply is missing when posting and replying on the Production Web Link.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1458]
**Describe the bug**
When posting and replying on the Production Web Link, the menu button on both post and reply is missing.

**To Reproduce**
1. Go to the Production Web Link. https://akasha.ethereum.world/social-app/feed
2. Log in to an account.
3. Share a post and reply on a post.
4. Check the menu button for the post and reply.

**Expected behavior**
The menu button should appear after posting and replying.

**Video**
https://user-images.githubusercontent.com/79607355/138589572-3de4f206-ccf1-4195-841f-bc982a5f9c1a.mp4

**Logs**
[MenuButton_Logs.txt](https://github.com/AKASHAorg/akasha-world-framework/files/7404487/MenuButton_Logs.txt)

**Screenshots**
![Screenshot_MenuButton](https://user-images.githubusercontent.com/79607355/138589368-cffb431f-6f2d-4e16-9ba3-3a3c81054859.jpg)

**Desktop (please complete the following information):**
- Dell Latitude E7440 | OS: Windows 10
- Browser: Chrome
- Version: 94.0.4606.81
- Browser: Brave Version
- Version: 95.1.31.87
- Browser: Firefox
- Version: 87.0.0.774

**Smartphone (please complete the following information):**
- Device: iPad Pro 9.7 (2016)
- OS: 14.4
- Browser: iOS MetaMask Browser
- Version: 3.4.1
- Browser: iOS Chrome
- Version: 95.0.4638.50
- Browser: iOS Safari
- Version: 14
- Device: Samsung Galaxy Note 8
- OS: 7.1.1
- Browser: iOS MetaMask Browser
- Version: 3.4.1
- Browser: Chrome 
- Version: 93.0.3577.82
- Device: iPhone SE2
- OS: 13.5.1
- Browser: Safari
- Version: 13

EP (RNR)
CC: @ggolcher

**Comment by ggolcher** [comment]
Invalid since it's on the current prod
