### ISSUE TITLE
Profile Does Not Update

### ISSUE THREAD

**Issue by AKASHAZERO** [AKASHAorg/akasha-world-framework#1468]
**Describe the bug**
My profile dashboard does not update.  This includes clicking the "update button."

"Posts", "Followers", "Following", and "Interests" do not update.  If I click to follow someone or a topic it does not work.  These problems existed before the update to v0.2 and have persisted after the update.

I have also lost all the topics I followed and a few of the people I followed.

**To Reproduce**
1. Go to Follow or update
2. Click on follow or update
3. Click refresh
4. Individual is not followed, profile is not updated. 

**Expected behavior**
Be able to follow people and update profile.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit) 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 10+
 - OS: Android 11; Build RP1A.200720.012
 - Browser: Brave 1.30.89, Chromium 94.0.4606.81
 - Version

**Additional context**

**Comment by SeverS** [comment]
It's fixed
