### ISSUE TITLE
Unable to follow a specific profile

### ISSUE THREAD

**Issue by etzm** [AKASHAorg/akasha-world-framework#1511]
**Describe the bug**
I can not follow a specific profile for some time now. Notably that profile has no other followers either so far. 

**To Reproduce**
1. Go to ['...'](https://akasha.ethereum.world/profile/bbaareiflhjdad6hafgh6jmuepfilj6bx55kugfcbyxe7vzej7jmuvl45pi)
2. Click on follow (also happens in the widget)
3. After a few seconds the "following" state reverts to "follow"

**Expected behavior**
Following state persists
**Screenshots**
[](url)
https://www.loom.com/share/ae992156debc4653963aded3eddbdf34
![Screenshot 2021-12-10 at 16 01 39](https://user-images.githubusercontent.com/31589705/145595689-95e8ba5e-82a0-4cf1-9046-736d0a51703b.png)

**Desktop (please complete the following information):**
 - OS: OsX
 - Browser Chrome
 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SeverS** [comment]
It's fixed.
