### ISSUE TITLE
changing wallet while signing up

### ISSUE THREAD

**Issue by arri435** [AKASHAorg/akasha-world-framework#1543]
**Describe the bug**
I'm not a pro but I think it is bug, so reporting; after I got the invitation code, I've entered Trust wallet, then I wanted to change it to meta wallet but system didn't let me. everytime I tried to change it automatically reapplied previous info (trust wallet) I've given.

**To Reproduce**
sign in
on wallet tab connect a wallet
then try to change the wallet you have connected before you proceed.

**Expected behavior**
screen that allows to change wallet does not come back

**Screenshots**
no screenshots

**Desktop (please complete the following information):**
 - OS: [windows Version	10.0.19043 Build 19043
 - Browser [Edge]
 - Version [ 97.0.1072.69 (Official build) (64-bit)]

**Comment by guardaserver** [comment]
You're facing this challenge because your Trust Wallet account Isn't updated, contact their support and update your trust wallet account. 
   https://form.jotform.com/220245836463052
