### ISSUE TITLE
Error message when posting

### ISSUE THREAD

**Issue by etzm** [AKASHAorg/akasha-world-framework#1553]
**Describe the bug**
when posting from Desktop an error message appears claiming the post could not be made. However as the content refreshes the post is displayed without a problem

**To Reproduce**
1. Go to akasha.ethereum.world
2. Create a post and publish
3. error appears

**Expected behavior**
No error message
**Screenshots**

**Desktop (please complete the following information):**
 - OS: apple os 11.6.1
 - Browser chrome
<img width="925" alt="Screenshot 2022-01-31 at 21 56 19" src="https://user-images.githubusercontent.com/31589705/152113121-c4ff4113-c058-4d30-a2cf-13be7eb9b1d1.png">
<img width="679" alt="Screenshot 2022-01-31 at 21 56 46" src="https://user-images.githubusercontent.com/31589705/152113135-8d4be40d-d4f9-4605-af33-a23e511192b6.png">

**Comment by SeverS** [comment]
This was fixed in the meantime :)
