### ISSUE TITLE
"Repost" (with comment) action not working from main post view

### ISSUE THREAD

**Issue by MihaiAlisie** [AKASHAorg/akasha-world-framework#752]
**Describe the bug**
When clicking the "Repost" icon and text nothing happens.

**To Reproduce**
1. Go to Feed
2. Click on any post to open it
3. Click "Repost"

**Expected behavior**
When clicking "Repost" (with comment) I would expect the editor to open with the original post showing as "quoted" - just like in the feed view.

**Desktop (please complete the following information):**
macOS Catalina 10.15.7 (19H2)
Firefox 85.0.2 (64-bit)
Signed up via Rainbow mobile wallet (iOS)

**Comment by kenshyx** [comment]
fixed!
