### ISSUE TITLE
Editing profile (on Desktop)

### ISSUE THREAD

**Issue by etzm** [AKASHAorg/akasha-world-framework#760]
**Describe the bug**
1. Using large images it takes forever
2. I have no option to crop/ adjust the part of image shown

**Expected behavior**
Images should be "tinyfied" before uploading, if that is possible so they do not take so long.
Editing images for profile tools should be provided.

**Additional context**

**Comment by kenshyx** [comment]
this also depends on textile buckets api upload speed, will close it now
