### ISSUE TITLE
Can upload multiple images by copying and pasting when drafting a post

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#795]
**Description**
I can upload an image, then copy and paste it into the editor

**Browser**
Mac, Chrome 88

**Steps to reproduce the behavior:**
Copy and paste an uploaded image

**Screenshots:**
![Screen Shot 2021-02-18 at 3 45 30 PM](https://user-images.githubusercontent.com/15471332/108430297-c545fa80-7206-11eb-8afd-edfc0e11f7bb.png)

**Comment by kenshyx** [comment]
no longer valid issue
