### ISSUE TITLE
The user is not redirected to the onboarding screen upon signing up for an account.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#844]
when the users signs up an account, the user is not redirected to the onboarding screen after going back to the browser.

1. Tap the Sign up button.
1. Tap the Scan with WalletConnect.
1. Tap the Connect button.
1. Connect the account.
1. Go back to the browser and observe the behavior.

Expected behavior:
The user should be redirected to the onboarding screen upon signing up for an account.

Desktop:

* Apple MacBook Air 13'2017
* OS: macOS High Sierra Version 10.13.6
* Browsers: Google Chrome Version Version 88.0.4324.182 | Safari 12 | Firefox Browser
* Version 86.0

Smartphone:

* Device: Google Pixel 2 XL
* OS: 11
* Browsers: Google Chrome Version: 88.0.4324.181
* iPhone 12 Pro
* OS: 14.4
* Browsers: Safari Version 14 | Chrome Version: 87.0.4280.77

https://user-images.githubusercontent.com/79607355/109131679-fb96f300-778d-11eb-8b92-42bb32a287f6.mp4

Wallet Used:

* MetaMask (App/Mobile)
* Metamask Web extension
* EP (ENC)

**Comment by kenshyx** [comment]
this was implemented, reopen if it still happens
