### ISSUE TITLE
[Android][Desktop Web] No description displayed on the Notifications UI when empty.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#846]
When the user doesn't have any notifications, it can be seen that there is no description displayed on the UI.

**To Reproduce**

1. Open https://ethereum-world.netlify.app/AKASHA-app/ on the web browser then sign in or sign up.
1. Proceed to the Notifications UI.
1. Observe if there is a description displayed on the UI.

**Expected behavior**

* A description should be displayed on the Notifications when empty.

**Screenshots**
**Actual issue**
![no description!UNITO-UNDERSCORE!notification!UNITO-UNDERSCORE!ui](https://user-images.githubusercontent.com/79607355/109133362-e753f580-778f-11eb-8adc-4b88c6a6fc0f.jpg)
**Design Doc**
![for reference!UNITO-UNDERSCORE!design!UNITO-UNDERSCORE!doc](https://user-images.githubusercontent.com/79607355/109133442-f9359880-778f-11eb-9825-b51d9b34b303.png)

**Desktop:**

* Apple MacBook Air 13'2017
* OS: macOS High Sierra Version 10.13.6
* Browser: Google Chrome Version Version 88.0.4324.182 | Safari 12 | Firefox Browser 
* Version [e.g. 22]
* Desktop 
* OS: Windows 10 Pro 
* Browsers: Google Chrome Version 88.0.4324.190 \| Firefox Browser Version 86.0 (64-bit)

**Smartphone:**

* Device: Xiaomi Pocophone F1
* OS: 10
* Google Chrome Version: 87.0.4280.141 | Firefox Browser Version 85.1.3

**Additional context**

* Based on the design, a " You have notifications. Post and replies in which you are tagged will appear here." text should be displayed below the text "All clear".
* Was not able to verify this issue on the iOS platform (Smartphone) due to an infinite loading encountered when accessing the UI.
* Was not able to verify this issue on the Mobile Firefox browser due to https://github.com/AKASHAorg/akasha-world-framework/issues/858.

**Wallet Used:**

* Metamask Mobile Wallet
* Metamask Web Extension

EP (NPP)

**Comment by kenshyx** [comment]
this was fixed
