### ISSUE TITLE
HTTML codes are appearing after accessing "Change Ethereum Name" UI.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#850]
When the user accesses the "Change Ethereum Name" UI, a HTTML codes appears on the UI.

1. On the Profile UI, click the "Edit Profile" button.
2. Choose the "Change Ethereum name".
3. Observe the UI.

Expected behavior:
There no HTTML should appear after accessing the "Change Ethereum Name" UI.

Screenshot:
![HTTML_ChangeEthereumName](https://user-images.githubusercontent.com/79607355/109138450-55e78200-7795-11eb-8adb-eb95451e1296.jpg)

Desktop:
Apple MacBook Air 13'2017
- OS: macOS High Sierra Version 10.13.6
- Browsers: Google Chrome Version Version 88.0.4324.182 | Safari 12 | Firefox Browser
- Version 86.0

Smartphone:
- Device: Google Pixel 2 XL
- OS: 11
- Browsers: Google Chrome Version: 88.0.4324.181
- iPhone 12 Pro
- OS: 14.4
- Browsers: Safari Version 14 | Chrome Version: 87.0.4280.77

**Wallet Used**
- Metamask Web extension
- Metamask (App/Mobile)

- EP (ENC)

**Comment by kenshyx** [comment]
this was fixed, reopen if it still happens
