### ISSUE TITLE
The "Connect a wallet" modal doesn't disappear after tapping the back button of the browser.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#868]
Describe the bug
when the user taps the Sign In or Sign Up button ( the "Connect a wallet" modal will pop up) while on the other page ( ex. member's profile) then the user taps the back button, the "Connect a wallet" modal button doesn't get removed.

To Reproduce

1. Open https://ethereum-world.netlify.app/AKASHA-app/ on the web browser.
1. Tap the member's profile.
1. Tap the Sign In or Sign Up button. (Connect a wallet modal will pop up.)
1. Tap the back button of the device or the browser.
1. Observe that the "Connect a wallet" modal is still appearing.

Expected behavior
The "Connect a wallet" modal should disappear once the user taps the back button.

Video:
https://user-images.githubusercontent.com/79607355/109193851-c3b29e80-77d3-11eb-8e89-df039bf1b045.mp4

Desktop:
HP Intel Pentium Silver	
OS: Windows 10 Home	
Browser: Google Chrome 
Version:  88.0.4324.182

Smartphones:
OnePlus 7T
OS: 10
Browser: Google Chrome
Version: 88.0.4324.181

iPhone XS Max
OS: 14.4
Browser: Safari
Version: 14

[AAT]

**Comment by ggolcher** [comment]
Confirmed fixed
