### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by marianagomes** [AKASHAorg/akasha-world-framework#920]
**Description**
- Remove suggestion popover on typing;
- Add number of results;
- Add filter by All/Profiles/Posts/Topics; 
- Update Profile and Topic cards on the results list;

--

**Invision Links**
[Desktop Search Typing](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenero7g01y501zndlppcxa4/play)
[Desktop Search Results](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenero7g01y601zn9npx7mx0/play#project_console)
[Desktop Search Scrolling](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenero7g01y701zn7tah6u8e/play#project_console)
[Desktop No Search Results](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenero7g01ya01zna0ch19hr/play#project_console)

[Mobile Search Typing](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenfjzhq01i001w654ux0o6m/play)
[Mobile Search Results](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28kmmn00hm01ux6wia3o2w/play#project_console)
[Mobile Search Scrolling](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenfjzhr01i201w6ebgs68i3/play#project_console)
[Mobile No Search Results](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckenfjzhr01i501w6h17hd8rv/play#project_console)

**Comment by ggolcher** [comment]
The back button is still not taking me away from search results.

**Comment by quininez** [comment]
How would that work considering that the search bar is available on all routes? And what if you just want to close the search bar, but not navigate away from the page you are currently on?

**Comment by ggolcher** [comment]
I'm describing the same behavior as Twitter on mobile.

When you do a search, you get search results. If you tap back, you go out of search mode and see the page you were on previously.

If you tap on a result, we open up the result for you without the search bar.

That way we don't change the page the user is in unless they're in the search results page.

**Comment by quininez** [comment]
So the back button will only work as a navigation if the user is on the search page, otherwise it will only close the search bar?

**Comment by ggolcher** [comment]
Play around with Twitter on mobile. When you tap on search results, the search bar closes.
