### ISSUE TITLE
Notifications Page

### ISSUE THREAD

**Issue by marianagomes** [AKASHAorg/akasha-world-framework#926]
**Description**
- Remove timeline;
- Translate the popover to a full page;

--

**Invision Links**
[Desktop Notifications](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm2828i200rg01xt9v6482s8/play)
[Desktop Notifications Mark all as read](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm2828i200rh01xt3tv97xxw/play#project_console)
[Desktop Notifications Hover](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm2828i200ri01xtgd1h04wh/play#project_console)
[Desktop Notifications Empty](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm2828i200rj01xtfkbjdrx2/play#project_console)

[Mobile Notifications](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28kmmm00hk01uxgjz25g6j/play)
[Mobile Notifications Empty](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28kmmn00hl01uxgf6q5eah/play#project_console)

**Comment by kenshyx** [comment]
completed with #1037
