### ISSUE TITLE
Legal Pages

### ISSUE THREAD

**Issue by marianagomes** [AKASHAorg/akasha-world-framework#930]
**Description**
- Create the legal pages;

--

**Invision Links**
[Desktop Access to Legal (Signed Out)](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28qa1r00ij01x57ezp9n01/play)
[Desktop Access to Legal Hover](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28qa1r00ik01x55nyc8yx9/play#project_console)
[Desktop Access to Legal Options Expanded](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckmeq20n901sl010s6hdgfy5s/play#project_console)

[Desktop Access to Legal (Signed In)](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28qa1r00ik01x55nyc8yx9/play#project_console)
[Desktop Access to Legal Options Expanded](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckmeq20n901sl010s6hdgfy5s/play#project_console)

[Desktop Legal Page Example](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28qa1r00im01x52fc707nl/play#project_console)

-

[Mobile Access to Legal (Signed Out)](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28r1yo00jz01wl28ksbr0n/play)

[Mobile Access to Legal (Signed In)](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28r1yo00k001wl07u05xc7/play#project_console)
[Mobile Access Legal Options Expanded](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28r1yo00k101wlazw37aw9/play#project_console)

[Mobile Legal Page Example](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckm28r1yo00k201wlhcv02gy5/play#project_console)

**Comment by ggolcher** [comment]
Confirmed fixed
