### ISSUE TITLE
Moderation: Reposts/Replies/Comments are not displayed for pending items

### ISSUE THREAD

**Issue by deiu** [AKASHAorg/akasha-world-framework#962]
**Describe the bug**
Reposts/Replies/Comments cannot currently be displayed when viewing the list of pending posts. This is a partial issue that comes from #837 and won't make it into v0.1.

**To Reproduce**
1. Go to the moderation app and click on the Pending tab.
2. Click on "Replies".
3. Nothing is displayed and the app takes you to the post view.

**Expected behavior**
Load comments and replies inline when clicking on the button.

**Comment by kenshyx** [comment]
can we close this?

**Comment by deiu** [comment]
I will close it for now. Not sure we need it right away.
