### ISSUE TITLE
Legal Requirements

### ISSUE THREAD

**Issue by marianagomes** [AKASHAorg/akasha-world-framework#970]
**Description**
- Add a cookie banner for the signed-out users;
- Add a step to accept the Terms;

**Invision**
[Desktop Cookies](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckmepq8bu01au01yhff7vejef/play)
[Desktop Accept the Terms](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckmeqz4f101pb010feko98ai0/play)

[Mobile Cookies](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckmepr2dc01sf010sgm6w0q71/play)
[Mobile Accept Terms](https://akasha.invisionapp.com/console/Ethereum-World-v0.1-R2-ckeneic0607vd017kd3ay7pj2/ckmer35la00zo01z87w7u094a/play)

**Comment by etzm** [comment]
I think this can be closed. @ggolcher @marianagomes

**Comment by ggolcher** [comment]
I agree, but it's marked as Dev To-Do. That's a decision from the devs.
