### ISSUE TITLE
The post with a tag is not listed on the Tag page when the user clicks the tag on the Trending Right Now.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#975]
**Describe the bug**
When the user posts with a tag that is included on the Trending Right Now and clicks the same tag on the Trending Right Now panel, the post is not listed on the Tag page.

**To Reproduce**
1. Go to the Feed UI.
2. Click on Share your thoughts.
3. Post anything with a tag that is included on the Trending Right Now.
4. Don't click the tag on the post.
5. Click on the same tag on the Trending Right Now.
6. Observe the listed posts.

**Expected behavior**
The post with the same tag should be included on the Tag page when the user clicks the tag on the Trending Right Now.

**Screenshots**
![Akasha_tags](https://user-images.githubusercontent.com/79607355/112111081-ae703a80-8bee-11eb-98e3-7c9f668857a2.png)
![akasha_tagpage](https://user-images.githubusercontent.com/79607355/112111111-b9c36600-8bee-11eb-8bfc-bfbf470e2a72.JPG)

**Desktop (please complete the following information):**

Acer Aspire 3
OS: Windows 10 home
Browser: Google Chrome Version | Firefox
Version: 89.0.4389.90 (Official Build) (64-bit) | 86.0.1

HP Omen Laptop3
OS: Windows 10 home
Browser: Google Chrome | Microsoft Edge
Version: 89.0.4389.90 (Official Build) (64-bit) | 89.0.774.57 (Official build) (64-bit)

MacBook Air 2019
OS: macOS Mojave 10.14.6
Browser: Google Chrome | Firefox
Version: 89.0.4389.90 | 86.0.1

**Additional context**
The issue occurs on any tags that are on Trending Right Now.

*Wallet Used:
 - MetaMask (Web extension)

(ACP)

**Comment by kenshyx** [comment]
this was fixed, reopen if it still happens 👯
