### ISSUE TITLE
The user is unable to publish a new post when it only consist a tag.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#976]
When the user inputs a tag on the 'New Post' textbox the Publish button is disabled.

**Steps to reproduce the behavior:**

1. On the Main UI, click the 'Share your thoughts' textbox.
1. Input a tag.
1. Observe the Publish button.

**Expected behavior**

* The user should be able to publish a new post even it only consists a tag.

**Video**
https://user-images.githubusercontent.com/79607355/112141963-fb650880-8c10-11eb-9b46-e5804f2beb84.mp4

**Desktop:**
Acer aspire 3

* OS: Windows 10 Home
* Browsers: Google Chrome | Firefox
* Version: 86.0.1

HP Omen Laptop

* Windows 10 Home
* Browsers: Microsoft Edge | Google Chrome
* Version: 89.0.774.57

MacBook Air 2019

* OS: macOS Mojave 10.14.6
* Browsers: Chrome Version | Firefox
* Version: 86.0.1

**Additional context**

* The team was not able to verify this issue on Mobile devices due to this bug #895.
* This issue is not occurring when adding a 'space' on the textbox.

**Wallet Used:**

* Metamask Web Extension

_EP (NMMT)_

**Comment by ggolcher** [comment]
![Screen Shot 2021-10-18 at 1 45 10 PM](https://user-images.githubusercontent.com/15471332/137788760-513e875c-9f61-47c3-b44a-f8fc31637644.png)

If I write the tag and then publish without putting in a space, it does not get called out as a tag.
