### ISSUE TITLE
The number of posts that use the tag on the Trending Right Now is not the same as the number of tag mentions and post list items on the Tags page.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#977]
**Describe the bug**
When the user clicks a tag in the Trending Right Now, the number of posts that use the tag is not the same as the number of tag mentions and post list items on the Tags page.

**To Reproduce**
1. Click on any tag in the Trending Right Now.
2. Observe the numbers of posts that use the tags on the Trending Right Now, tag mentions, and post list items on the Tags page. 

**Expected behavior**
The number of posts that use the tags on the Trending Right Now should be the same as the number of tag mentions and post list items on the Tags page.

**Screenshots**
![akasha_numbers](https://user-images.githubusercontent.com/79607355/112139541-d622cb00-8c0d-11eb-9ff3-a24f5d7fdb39.png)
![akasha_post list](https://user-images.githubusercontent.com/79607355/112139562-dde26f80-8c0d-11eb-8103-df67b8d84658.JPG)

**Desktop:**
 Acer Aspire 3
OS: Windows 10 home
Browser: Google Chrome Version | Firefox
Version: 89.0.4389.90 (Official Build) (64-bit) | 86.0.1

HP Omen Laptop3
OS: Windows 10 home
Browser: Google Chrome | Microsoft Edge
Version: 89.0.4389.90 (Official Build) (64-bit) | 89.0.774.57 (Official build) (64-bit)

MacBook Air 2019
OS: macOS Mojave 10.14.6
Browser: Google Chrome | Firefox
Version: 89.0.4389.90 | 86.0.1

*Wallet Used:
-MetaMask (Web extension)

(ACP)

**Comment by kenshyx** [comment]
this was fixed, reopen if it still happens 👯
