### ISSUE TITLE
Stuck in the profile editor

### ISSUE THREAD

**Issue by sheldrake** [AKASHAorg/akasha-world-framework#986]
**Describe the bug**
I got stuck in the profile editor with no way to exit other than to refresh the browser.

**To Reproduce**
1. On logging in I was prompted to add a profile name (I had tried a few weeks back but it wasn't working for me at that stage).
2. I set my profile name to "Sheldrake"
3. I set my profile username to "@sheldrake"
4. I clicked Save
5. Without first refreshing or doing anything else, I clicked "Edit profile"
6. The dropdown gave just one of the two options normally shown — "Update profile"
7. I then found myself with the popover with no option to Cancel and with Save greyed out. I had to refresh my browser tab to continue using Ethereum World.

**Expected behavior**
I would expect the behaviour from step 6 above that I now get on refreshing — two options show "Update profile" and "Change Ethereum name" (why is it to as Ethereum name here and username elsewhere?)

I would expect on clicking "Update profile" for it to show both the Cancel and Save buttons with neither greyed out.

**Screenshots**
![Screenshot 2021-03-24 at 11 36 19](https://user-images.githubusercontent.com/208643/112297429-cc40ac80-8c8d-11eb-9091-0413deeb4ef0.png)

**Desktop (please complete the following information):**
 - Mac OS Big Sur 11.2.3
 - FF 86

**Comment by kenshyx** [comment]
this was fixed in #988
