### ISSUE TITLE
Cannot reply to a post a second time.

### ISSUE THREAD

**Issue by sheldrake** [AKASHAorg/akasha-world-framework#987]
**Describe the bug**
First reply working. Subsequent attempts to reply to the same post not working.

**To Reproduce**
1. Andrei posted.
2. I replied.
3. The reply counter incremented to 1 and my reply with displayed.
4. I went to reply again (to acknowledge a spelling mistake 😮)
5. My second reply was displayed but the counter did not increment
6. So thought I'd check to see if the counter would increment upon refreshing but found that my second comment disappeared instead. The good news is the comment counter was now correct 🤪

**Expected behavior**
I would expect to post a second time, for it to be displayed, and for the counter to increment accordingly, without needing to refresh.

**Screenshots**
![Screenshot 2021-03-24 at 11 47 51](https://user-images.githubusercontent.com/208643/112298762-1a09e480-8c8f-11eb-86f9-beba3191b941.png)

![Screenshot 2021-03-24 at 11 47 59](https://user-images.githubusercontent.com/208643/112298808-1c6c3e80-8c8f-11eb-8efe-3d0269622e3a.png)

**Desktop (please complete the following information):**
 - MacOS Big Sur 11.2.3
 - FF 86

**Comment by kenshyx** [comment]
this was fixed, reopen if it still happens 👯
